// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LogEntry is a single structured log record forwarded from the helper
 * to the GUI (and from the GUI to the frontend LogViewer). We keep it flat
 * — no nested attrs — because the viewer just renders a one-line per entry.
 */
export class LogEntry {
    /**
     * Creates a new LogEntry instance.
     * @param {Partial<LogEntry>} [$$source = {}] - The source object to create the LogEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * RFC3339
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * "debug" | "info" | "warn" | "error"
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "helper" | "gui"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * human-readable text (already includes attrs)
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogEntry(/** @type {Partial<LogEntry>} */($$parsedSource));
    }
}

/**
 * SettingsChangedPayload carries a single applied setting so a running
 * GUI can reflect a change made through another client (the CLI). Only
 * the field for the changed setting is non-nil.
 */
export class SettingsChangedPayload {
    /**
     * Creates a new SettingsChangedPayload instance.
     * @param {Partial<SettingsChangedPayload>} [$$source = {}] - The source object to create the SettingsChangedPayload.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["kill_switch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["dns_protection"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["health_check"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | null | undefined}
             */
            this["pin_interface"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["log_level"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsChangedPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsChangedPayload}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsChangedPayload(/** @type {Partial<SettingsChangedPayload>} */($$parsedSource));
    }
}
