// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/wireguide.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TunnelName     string                 `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	ScriptsAllowed bool                   `protobuf:"varint,2,opt,name=scripts_allowed,json=scriptsAllowed,proto3" json:"scripts_allowed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

func (x *ConnectRequest) GetScriptsAllowed() bool {
	if x != nil {
		return x.ScriptsAllowed
	}
	return false
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{1}
}

type DisconnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectRequest) Reset() {
	*x = DisconnectRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectRequest) ProtoMessage() {}

func (x *DisconnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectRequest.ProtoReflect.Descriptor instead.
func (*DisconnectRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{2}
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{3}
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{4}
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*TunnelInfo          `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{5}
}

func (x *ListTunnelsResponse) GetTunnels() []*TunnelInfo {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type TunnelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsConnected   bool                   `protobuf:"varint,2,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	HasScripts    bool                   `protobuf:"varint,4,opt,name=has_scripts,json=hasScripts,proto3" json:"has_scripts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelInfo) Reset() {
	*x = TunnelInfo{}
	mi := &file_proto_wireguide_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelInfo) ProtoMessage() {}

func (x *TunnelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelInfo.ProtoReflect.Descriptor instead.
func (*TunnelInfo) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{6}
}

func (x *TunnelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelInfo) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *TunnelInfo) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *TunnelInfo) GetHasScripts() bool {
	if x != nil {
		return x.HasScripts
	}
	return false
}

type GetTunnelDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelDetailRequest) Reset() {
	*x = GetTunnelDetailRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelDetailRequest) ProtoMessage() {}

func (x *GetTunnelDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelDetailRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{7}
}

func (x *GetTunnelDetailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TunnelDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InterfaceConfig *InterfaceConfig       `protobuf:"bytes,2,opt,name=interface_config,json=interfaceConfig,proto3" json:"interface_config,omitempty"`
	Peers           []*PeerConfig          `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TunnelDetail) Reset() {
	*x = TunnelDetail{}
	mi := &file_proto_wireguide_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelDetail) ProtoMessage() {}

func (x *TunnelDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelDetail.ProtoReflect.Descriptor instead.
func (*TunnelDetail) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{8}
}

func (x *TunnelDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TunnelDetail) GetInterfaceConfig() *InterfaceConfig {
	if x != nil {
		return x.InterfaceConfig
	}
	return nil
}

func (x *TunnelDetail) GetPeers() []*PeerConfig {
	if x != nil {
		return x.Peers
	}
	return nil
}

type InterfaceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []string               `protobuf:"bytes,1,rep,name=address,proto3" json:"address,omitempty"`
	Dns           []string               `protobuf:"bytes,2,rep,name=dns,proto3" json:"dns,omitempty"`
	Mtu           int32                  `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	ListenPort    int32                  `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	PreUp         string                 `protobuf:"bytes,5,opt,name=pre_up,json=preUp,proto3" json:"pre_up,omitempty"`
	PostUp        string                 `protobuf:"bytes,6,opt,name=post_up,json=postUp,proto3" json:"post_up,omitempty"`
	PreDown       string                 `protobuf:"bytes,7,opt,name=pre_down,json=preDown,proto3" json:"pre_down,omitempty"`
	PostDown      string                 `protobuf:"bytes,8,opt,name=post_down,json=postDown,proto3" json:"post_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceConfig) Reset() {
	*x = InterfaceConfig{}
	mi := &file_proto_wireguide_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceConfig) ProtoMessage() {}

func (x *InterfaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceConfig.ProtoReflect.Descriptor instead.
func (*InterfaceConfig) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{9}
}

func (x *InterfaceConfig) GetAddress() []string {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *InterfaceConfig) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

func (x *InterfaceConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *InterfaceConfig) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *InterfaceConfig) GetPreUp() string {
	if x != nil {
		return x.PreUp
	}
	return ""
}

func (x *InterfaceConfig) GetPostUp() string {
	if x != nil {
		return x.PostUp
	}
	return ""
}

func (x *InterfaceConfig) GetPreDown() string {
	if x != nil {
		return x.PreDown
	}
	return ""
}

func (x *InterfaceConfig) GetPostDown() string {
	if x != nil {
		return x.PostDown
	}
	return ""
}

type PeerConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PublicKey           string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint            string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps          []string               `protobuf:"bytes,3,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PersistentKeepalive int32                  `protobuf:"varint,4,opt,name=persistent_keepalive,json=persistentKeepalive,proto3" json:"persistent_keepalive,omitempty"`
	HasPresharedKey     bool                   `protobuf:"varint,5,opt,name=has_preshared_key,json=hasPresharedKey,proto3" json:"has_preshared_key,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PeerConfig) Reset() {
	*x = PeerConfig{}
	mi := &file_proto_wireguide_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConfig) ProtoMessage() {}

func (x *PeerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConfig.ProtoReflect.Descriptor instead.
func (*PeerConfig) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{10}
}

func (x *PeerConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *PeerConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerConfig) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *PeerConfig) GetPersistentKeepalive() int32 {
	if x != nil {
		return x.PersistentKeepalive
	}
	return 0
}

func (x *PeerConfig) GetHasPresharedKey() bool {
	if x != nil {
		return x.HasPresharedKey
	}
	return false
}

type StreamStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStatusRequest) Reset() {
	*x = StreamStatusRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStatusRequest) ProtoMessage() {}

func (x *StreamStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStatusRequest.ProtoReflect.Descriptor instead.
func (*StreamStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{11}
}

type ConnectionStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	State            string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"` // disconnected, connecting, connected, error, reconnecting
	TunnelName       string                 `protobuf:"bytes,2,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	InterfaceName    string                 `protobuf:"bytes,3,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	RxBytes          int64                  `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes          int64                  `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshake    string                 `protobuf:"bytes,6,opt,name=last_handshake,json=lastHandshake,proto3" json:"last_handshake,omitempty"` // human-readable age
	Duration         string                 `protobuf:"bytes,7,opt,name=duration,proto3" json:"duration,omitempty"`                                // human-readable duration
	Endpoint         string                 `protobuf:"bytes,8,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReconnectAttempt int32                  `protobuf:"varint,10,opt,name=reconnect_attempt,json=reconnectAttempt,proto3" json:"reconnect_attempt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_proto_wireguide_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{12}
}

func (x *ConnectionStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ConnectionStatus) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

func (x *ConnectionStatus) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *ConnectionStatus) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *ConnectionStatus) GetTxBytes() int64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *ConnectionStatus) GetLastHandshake() string {
	if x != nil {
		return x.LastHandshake
	}
	return ""
}

func (x *ConnectionStatus) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *ConnectionStatus) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *ConnectionStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ConnectionStatus) GetReconnectAttempt() int32 {
	if x != nil {
		return x.ReconnectAttempt
	}
	return 0
}

type ImportConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportConfigRequest) Reset() {
	*x = ImportConfigRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportConfigRequest) ProtoMessage() {}

func (x *ImportConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportConfigRequest.ProtoReflect.Descriptor instead.
func (*ImportConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{13}
}

func (x *ImportConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImportConfigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ImportConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *TunnelInfo            `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportConfigResponse) Reset() {
	*x = ImportConfigResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportConfigResponse) ProtoMessage() {}

func (x *ImportConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportConfigResponse.ProtoReflect.Descriptor instead.
func (*ImportConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{14}
}

func (x *ImportConfigResponse) GetTunnel() *TunnelInfo {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateConfigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []string               `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateConfigResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type GetConfigTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigTextRequest) Reset() {
	*x = GetConfigTextRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigTextRequest) ProtoMessage() {}

func (x *GetConfigTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigTextRequest.ProtoReflect.Descriptor instead.
func (*GetConfigTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{17}
}

func (x *GetConfigTextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetConfigTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigTextResponse) Reset() {
	*x = GetConfigTextResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigTextResponse) ProtoMessage() {}

func (x *GetConfigTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigTextResponse.ProtoReflect.Descriptor instead.
func (*GetConfigTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{18}
}

func (x *GetConfigTextResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConfigRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{20}
}

type DeleteTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelRequest) Reset() {
	*x = DeleteTunnelRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelRequest) ProtoMessage() {}

func (x *DeleteTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelRequest.ProtoReflect.Descriptor instead.
func (*DeleteTunnelRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelResponse) Reset() {
	*x = DeleteTunnelResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelResponse) ProtoMessage() {}

func (x *DeleteTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelResponse.ProtoReflect.Descriptor instead.
func (*DeleteTunnelResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{22}
}

type ExportConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportConfigRequest) Reset() {
	*x = ExportConfigRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportConfigRequest) ProtoMessage() {}

func (x *ExportConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportConfigRequest.ProtoReflect.Descriptor instead.
func (*ExportConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{23}
}

func (x *ExportConfigRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExportConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportConfigResponse) Reset() {
	*x = ExportConfigResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportConfigResponse) ProtoMessage() {}

func (x *ExportConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportConfigResponse.ProtoReflect.Descriptor instead.
func (*ExportConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{24}
}

func (x *ExportConfigResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type TunnelExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelExistsRequest) Reset() {
	*x = TunnelExistsRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelExistsRequest) ProtoMessage() {}

func (x *TunnelExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelExistsRequest.ProtoReflect.Descriptor instead.
func (*TunnelExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{25}
}

func (x *TunnelExistsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TunnelExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelExistsResponse) Reset() {
	*x = TunnelExistsResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelExistsResponse) ProtoMessage() {}

func (x *TunnelExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelExistsResponse.ProtoReflect.Descriptor instead.
func (*TunnelExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{26}
}

func (x *TunnelExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type Settings struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Language          string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Theme             string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme,omitempty"`
	TrayIconStyle     string                 `protobuf:"bytes,3,opt,name=tray_icon_style,json=trayIconStyle,proto3" json:"tray_icon_style,omitempty"`
	AutoReconnect     bool                   `protobuf:"varint,4,opt,name=auto_reconnect,json=autoReconnect,proto3" json:"auto_reconnect,omitempty"`
	KillSwitch        bool                   `protobuf:"varint,5,opt,name=kill_switch,json=killSwitch,proto3" json:"kill_switch,omitempty"`
	DnsProtection     bool                   `protobuf:"varint,6,opt,name=dns_protection,json=dnsProtection,proto3" json:"dns_protection,omitempty"`
	LogLevel          string                 `protobuf:"bytes,7,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	AutoStart         bool                   `protobuf:"varint,8,opt,name=auto_start,json=autoStart,proto3" json:"auto_start,omitempty"`
	AutoConnectTunnel string                 `protobuf:"bytes,9,opt,name=auto_connect_tunnel,json=autoConnectTunnel,proto3" json:"auto_connect_tunnel,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_proto_wireguide_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{27}
}

func (x *Settings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Settings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Settings) GetTrayIconStyle() string {
	if x != nil {
		return x.TrayIconStyle
	}
	return ""
}

func (x *Settings) GetAutoReconnect() bool {
	if x != nil {
		return x.AutoReconnect
	}
	return false
}

func (x *Settings) GetKillSwitch() bool {
	if x != nil {
		return x.KillSwitch
	}
	return false
}

func (x *Settings) GetDnsProtection() bool {
	if x != nil {
		return x.DnsProtection
	}
	return false
}

func (x *Settings) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *Settings) GetAutoStart() bool {
	if x != nil {
		return x.AutoStart
	}
	return false
}

func (x *Settings) GetAutoConnectTunnel() string {
	if x != nil {
		return x.AutoConnectTunnel
	}
	return ""
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{28}
}

type SaveSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveSettingsResponse) Reset() {
	*x = SaveSettingsResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveSettingsResponse) ProtoMessage() {}

func (x *SaveSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveSettingsResponse.ProtoReflect.Descriptor instead.
func (*SaveSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{29}
}

type SetKillSwitchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKillSwitchRequest) Reset() {
	*x = SetKillSwitchRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKillSwitchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKillSwitchRequest) ProtoMessage() {}

func (x *SetKillSwitchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKillSwitchRequest.ProtoReflect.Descriptor instead.
func (*SetKillSwitchRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{30}
}

func (x *SetKillSwitchRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetKillSwitchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetKillSwitchResponse) Reset() {
	*x = SetKillSwitchResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetKillSwitchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetKillSwitchResponse) ProtoMessage() {}

func (x *SetKillSwitchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetKillSwitchResponse.ProtoReflect.Descriptor instead.
func (*SetKillSwitchResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{31}
}

type SetDNSProtectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDNSProtectionRequest) Reset() {
	*x = SetDNSProtectionRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDNSProtectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSProtectionRequest) ProtoMessage() {}

func (x *SetDNSProtectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSProtectionRequest.ProtoReflect.Descriptor instead.
func (*SetDNSProtectionRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{32}
}

func (x *SetDNSProtectionRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetDNSProtectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDNSProtectionResponse) Reset() {
	*x = SetDNSProtectionResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDNSProtectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDNSProtectionResponse) ProtoMessage() {}

func (x *SetDNSProtectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDNSProtectionResponse.ProtoReflect.Descriptor instead.
func (*SetDNSProtectionResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{33}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_wireguide_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{34}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_wireguide_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wireguide_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_wireguide_proto_rawDescGZIP(), []int{35}
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_wireguide_proto protoreflect.FileDescriptor

const file_proto_wireguide_proto_rawDesc = "" +
	"\n" +
	"\x15proto/wireguide.proto\x12\twireguide\"Z\n" +
	"\x0eConnectRequest\x12\x1f\n" +
	"\vtunnel_name\x18\x01 \x01(\tR\n" +
	"tunnelName\x12'\n" +
	"\x0fscripts_allowed\x18\x02 \x01(\bR\x0escriptsAllowed\"\x11\n" +
	"\x0fConnectResponse\"\x13\n" +
	"\x11DisconnectRequest\"\x14\n" +
	"\x12DisconnectResponse\"\x14\n" +
	"\x12ListTunnelsRequest\"F\n" +
	"\x13ListTunnelsResponse\x12/\n" +
	"\atunnels\x18\x01 \x03(\v2\x15.wireguide.TunnelInfoR\atunnels\"\x80\x01\n" +
	"\n" +
	"TunnelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fis_connected\x18\x02 \x01(\bR\visConnected\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vhas_scripts\x18\x04 \x01(\bR\n" +
	"hasScripts\",\n" +
	"\x16GetTunnelDetailRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x96\x01\n" +
	"\fTunnelDetail\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12E\n" +
	"\x10interface_config\x18\x02 \x01(\v2\x1a.wireguide.InterfaceConfigR\x0finterfaceConfig\x12+\n" +
	"\x05peers\x18\x03 \x03(\v2\x15.wireguide.PeerConfigR\x05peers\"\xd8\x01\n" +
	"\x0fInterfaceConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x03(\tR\aaddress\x12\x10\n" +
	"\x03dns\x18\x02 \x03(\tR\x03dns\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\x05R\x03mtu\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\x05R\n" +
	"listenPort\x12\x15\n" +
	"\x06pre_up\x18\x05 \x01(\tR\x05preUp\x12\x17\n" +
	"\apost_up\x18\x06 \x01(\tR\x06postUp\x12\x19\n" +
	"\bpre_down\x18\a \x01(\tR\apreDown\x12\x1b\n" +
	"\tpost_down\x18\b \x01(\tR\bpostDown\"\xc7\x01\n" +
	"\n" +
	"PeerConfig\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x03(\tR\n" +
	"allowedIps\x121\n" +
	"\x14persistent_keepalive\x18\x04 \x01(\x05R\x13persistentKeepalive\x12*\n" +
	"\x11has_preshared_key\x18\x05 \x01(\bR\x0fhasPresharedKey\"\x15\n" +
	"\x13StreamStatusRequest\"\xd7\x02\n" +
	"\x10ConnectionStatus\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x1f\n" +
	"\vtunnel_name\x18\x02 \x01(\tR\n" +
	"tunnelName\x12%\n" +
	"\x0einterface_name\x18\x03 \x01(\tR\rinterfaceName\x12\x19\n" +
	"\brx_bytes\x18\x04 \x01(\x03R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x03R\atxBytes\x12%\n" +
	"\x0elast_handshake\x18\x06 \x01(\tR\rlastHandshake\x12\x1a\n" +
	"\bduration\x18\a \x01(\tR\bduration\x12\x1a\n" +
	"\bendpoint\x18\b \x01(\tR\bendpoint\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12+\n" +
	"\x11reconnect_attempt\x18\n" +
	" \x01(\x05R\x10reconnectAttempt\"C\n" +
	"\x13ImportConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"E\n" +
	"\x14ImportConfigResponse\x12-\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x15.wireguide.TunnelInfoR\x06tunnel\"1\n" +
	"\x15ValidateConfigRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"0\n" +
	"\x16ValidateConfigResponse\x12\x16\n" +
	"\x06errors\x18\x01 \x03(\tR\x06errors\"*\n" +
	"\x14GetConfigTextRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x15GetConfigTextResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"C\n" +
	"\x13UpdateConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x16\n" +
	"\x14UpdateConfigResponse\")\n" +
	"\x13DeleteTunnelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteTunnelResponse\")\n" +
	"\x13ExportConfigRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x14ExportConfigResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\")\n" +
	"\x13TunnelExistsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x14TunnelExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\xbf\x02\n" +
	"\bSettings\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x12&\n" +
	"\x0ftray_icon_style\x18\x03 \x01(\tR\rtrayIconStyle\x12%\n" +
	"\x0eauto_reconnect\x18\x04 \x01(\bR\rautoReconnect\x12\x1f\n" +
	"\vkill_switch\x18\x05 \x01(\bR\n" +
	"killSwitch\x12%\n" +
	"\x0edns_protection\x18\x06 \x01(\bR\rdnsProtection\x12\x1b\n" +
	"\tlog_level\x18\a \x01(\tR\blogLevel\x12\x1d\n" +
	"\n" +
	"auto_start\x18\b \x01(\bR\tautoStart\x12.\n" +
	"\x13auto_connect_tunnel\x18\t \x01(\tR\x11autoConnectTunnel\"\x14\n" +
	"\x12GetSettingsRequest\"\x16\n" +
	"\x14SaveSettingsResponse\"0\n" +
	"\x14SetKillSwitchRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x17\n" +
	"\x15SetKillSwitchResponse\"3\n" +
	"\x17SetDNSProtectionRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x1a\n" +
	"\x18SetDNSProtectionResponse\"\r\n" +
	"\vPingRequest\"@\n" +
	"\fPingResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xbe\n" +
	"\n" +
	"\x10WireGuideService\x12@\n" +
	"\aConnect\x12\x19.wireguide.ConnectRequest\x1a\x1a.wireguide.ConnectResponse\x12I\n" +
	"\n" +
	"Disconnect\x12\x1c.wireguide.DisconnectRequest\x1a\x1d.wireguide.DisconnectResponse\x12L\n" +
	"\vListTunnels\x12\x1d.wireguide.ListTunnelsRequest\x1a\x1e.wireguide.ListTunnelsResponse\x12M\n" +
	"\x0fGetTunnelDetail\x12!.wireguide.GetTunnelDetailRequest\x1a\x17.wireguide.TunnelDetail\x12M\n" +
	"\fStreamStatus\x12\x1e.wireguide.StreamStatusRequest\x1a\x1b.wireguide.ConnectionStatus0\x01\x12O\n" +
	"\fImportConfig\x12\x1e.wireguide.ImportConfigRequest\x1a\x1f.wireguide.ImportConfigResponse\x12U\n" +
	"\x0eValidateConfig\x12 .wireguide.ValidateConfigRequest\x1a!.wireguide.ValidateConfigResponse\x12R\n" +
	"\rGetConfigText\x12\x1f.wireguide.GetConfigTextRequest\x1a .wireguide.GetConfigTextResponse\x12O\n" +
	"\fUpdateConfig\x12\x1e.wireguide.UpdateConfigRequest\x1a\x1f.wireguide.UpdateConfigResponse\x12O\n" +
	"\fDeleteTunnel\x12\x1e.wireguide.DeleteTunnelRequest\x1a\x1f.wireguide.DeleteTunnelResponse\x12O\n" +
	"\fExportConfig\x12\x1e.wireguide.ExportConfigRequest\x1a\x1f.wireguide.ExportConfigResponse\x12O\n" +
	"\fTunnelExists\x12\x1e.wireguide.TunnelExistsRequest\x1a\x1f.wireguide.TunnelExistsResponse\x12A\n" +
	"\vGetSettings\x12\x1d.wireguide.GetSettingsRequest\x1a\x13.wireguide.Settings\x12D\n" +
	"\fSaveSettings\x12\x13.wireguide.Settings\x1a\x1f.wireguide.SaveSettingsResponse\x12R\n" +
	"\rSetKillSwitch\x12\x1f.wireguide.SetKillSwitchRequest\x1a .wireguide.SetKillSwitchResponse\x12[\n" +
	"\x10SetDNSProtection\x12\".wireguide.SetDNSProtectionRequest\x1a#.wireguide.SetDNSProtectionResponse\x127\n" +
	"\x04Ping\x12\x16.wireguide.PingRequest\x1a\x17.wireguide.PingResponseB1Z/github.com/korjwl1/wireguide/internal/ipc/protob\x06proto3"

var (
	file_proto_wireguide_proto_rawDescOnce sync.Once
	file_proto_wireguide_proto_rawDescData []byte
)

func file_proto_wireguide_proto_rawDescGZIP() []byte {
	file_proto_wireguide_proto_rawDescOnce.Do(func() {
		file_proto_wireguide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wireguide_proto_rawDesc), len(file_proto_wireguide_proto_rawDesc)))
	})
	return file_proto_wireguide_proto_rawDescData
}

var file_proto_wireguide_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_proto_wireguide_proto_goTypes = []any{
	(*ConnectRequest)(nil),           // 0: wireguide.ConnectRequest
	(*ConnectResponse)(nil),          // 1: wireguide.ConnectResponse
	(*DisconnectRequest)(nil),        // 2: wireguide.DisconnectRequest
	(*DisconnectResponse)(nil),       // 3: wireguide.DisconnectResponse
	(*ListTunnelsRequest)(nil),       // 4: wireguide.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),      // 5: wireguide.ListTunnelsResponse
	(*TunnelInfo)(nil),               // 6: wireguide.TunnelInfo
	(*GetTunnelDetailRequest)(nil),   // 7: wireguide.GetTunnelDetailRequest
	(*TunnelDetail)(nil),             // 8: wireguide.TunnelDetail
	(*InterfaceConfig)(nil),          // 9: wireguide.InterfaceConfig
	(*PeerConfig)(nil),               // 10: wireguide.PeerConfig
	(*StreamStatusRequest)(nil),      // 11: wireguide.StreamStatusRequest
	(*ConnectionStatus)(nil),         // 12: wireguide.ConnectionStatus
	(*ImportConfigRequest)(nil),      // 13: wireguide.ImportConfigRequest
	(*ImportConfigResponse)(nil),     // 14: wireguide.ImportConfigResponse
	(*ValidateConfigRequest)(nil),    // 15: wireguide.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),   // 16: wireguide.ValidateConfigResponse
	(*GetConfigTextRequest)(nil),     // 17: wireguide.GetConfigTextRequest
	(*GetConfigTextResponse)(nil),    // 18: wireguide.GetConfigTextResponse
	(*UpdateConfigRequest)(nil),      // 19: wireguide.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),     // 20: wireguide.UpdateConfigResponse
	(*DeleteTunnelRequest)(nil),      // 21: wireguide.DeleteTunnelRequest
	(*DeleteTunnelResponse)(nil),     // 22: wireguide.DeleteTunnelResponse
	(*ExportConfigRequest)(nil),      // 23: wireguide.ExportConfigRequest
	(*ExportConfigResponse)(nil),     // 24: wireguide.ExportConfigResponse
	(*TunnelExistsRequest)(nil),      // 25: wireguide.TunnelExistsRequest
	(*TunnelExistsResponse)(nil),     // 26: wireguide.TunnelExistsResponse
	(*Settings)(nil),                 // 27: wireguide.Settings
	(*GetSettingsRequest)(nil),       // 28: wireguide.GetSettingsRequest
	(*SaveSettingsResponse)(nil),     // 29: wireguide.SaveSettingsResponse
	(*SetKillSwitchRequest)(nil),     // 30: wireguide.SetKillSwitchRequest
	(*SetKillSwitchResponse)(nil),    // 31: wireguide.SetKillSwitchResponse
	(*SetDNSProtectionRequest)(nil),  // 32: wireguide.SetDNSProtectionRequest
	(*SetDNSProtectionResponse)(nil), // 33: wireguide.SetDNSProtectionResponse
	(*PingRequest)(nil),              // 34: wireguide.PingRequest
	(*PingResponse)(nil),             // 35: wireguide.PingResponse
}
var file_proto_wireguide_proto_depIdxs = []int32{
	6,  // 0: wireguide.ListTunnelsResponse.tunnels:type_name -> wireguide.TunnelInfo
	9,  // 1: wireguide.TunnelDetail.interface_config:type_name -> wireguide.InterfaceConfig
	10, // 2: wireguide.TunnelDetail.peers:type_name -> wireguide.PeerConfig
	6,  // 3: wireguide.ImportConfigResponse.tunnel:type_name -> wireguide.TunnelInfo
	0,  // 4: wireguide.WireGuideService.Connect:input_type -> wireguide.ConnectRequest
	2,  // 5: wireguide.WireGuideService.Disconnect:input_type -> wireguide.DisconnectRequest
	4,  // 6: wireguide.WireGuideService.ListTunnels:input_type -> wireguide.ListTunnelsRequest
	7,  // 7: wireguide.WireGuideService.GetTunnelDetail:input_type -> wireguide.GetTunnelDetailRequest
	11, // 8: wireguide.WireGuideService.StreamStatus:input_type -> wireguide.StreamStatusRequest
	13, // 9: wireguide.WireGuideService.ImportConfig:input_type -> wireguide.ImportConfigRequest
	15, // 10: wireguide.WireGuideService.ValidateConfig:input_type -> wireguide.ValidateConfigRequest
	17, // 11: wireguide.WireGuideService.GetConfigText:input_type -> wireguide.GetConfigTextRequest
	19, // 12: wireguide.WireGuideService.UpdateConfig:input_type -> wireguide.UpdateConfigRequest
	21, // 13: wireguide.WireGuideService.DeleteTunnel:input_type -> wireguide.DeleteTunnelRequest
	23, // 14: wireguide.WireGuideService.ExportConfig:input_type -> wireguide.ExportConfigRequest
	25, // 15: wireguide.WireGuideService.TunnelExists:input_type -> wireguide.TunnelExistsRequest
	28, // 16: wireguide.WireGuideService.GetSettings:input_type -> wireguide.GetSettingsRequest
	27, // 17: wireguide.WireGuideService.SaveSettings:input_type -> wireguide.Settings
	30, // 18: wireguide.WireGuideService.SetKillSwitch:input_type -> wireguide.SetKillSwitchRequest
	32, // 19: wireguide.WireGuideService.SetDNSProtection:input_type -> wireguide.SetDNSProtectionRequest
	34, // 20: wireguide.WireGuideService.Ping:input_type -> wireguide.PingRequest
	1,  // 21: wireguide.WireGuideService.Connect:output_type -> wireguide.ConnectResponse
	3,  // 22: wireguide.WireGuideService.Disconnect:output_type -> wireguide.DisconnectResponse
	5,  // 23: wireguide.WireGuideService.ListTunnels:output_type -> wireguide.ListTunnelsResponse
	8,  // 24: wireguide.WireGuideService.GetTunnelDetail:output_type -> wireguide.TunnelDetail
	12, // 25: wireguide.WireGuideService.StreamStatus:output_type -> wireguide.ConnectionStatus
	14, // 26: wireguide.WireGuideService.ImportConfig:output_type -> wireguide.ImportConfigResponse
	16, // 27: wireguide.WireGuideService.ValidateConfig:output_type -> wireguide.ValidateConfigResponse
	18, // 28: wireguide.WireGuideService.GetConfigText:output_type -> wireguide.GetConfigTextResponse
	20, // 29: wireguide.WireGuideService.UpdateConfig:output_type -> wireguide.UpdateConfigResponse
	22, // 30: wireguide.WireGuideService.DeleteTunnel:output_type -> wireguide.DeleteTunnelResponse
	24, // 31: wireguide.WireGuideService.ExportConfig:output_type -> wireguide.ExportConfigResponse
	26, // 32: wireguide.WireGuideService.TunnelExists:output_type -> wireguide.TunnelExistsResponse
	27, // 33: wireguide.WireGuideService.GetSettings:output_type -> wireguide.Settings
	29, // 34: wireguide.WireGuideService.SaveSettings:output_type -> wireguide.SaveSettingsResponse
	31, // 35: wireguide.WireGuideService.SetKillSwitch:output_type -> wireguide.SetKillSwitchResponse
	33, // 36: wireguide.WireGuideService.SetDNSProtection:output_type -> wireguide.SetDNSProtectionResponse
	35, // 37: wireguide.WireGuideService.Ping:output_type -> wireguide.PingResponse
	21, // [21:38] is the sub-list for method output_type
	4,  // [4:21] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_wireguide_proto_init() }
func file_proto_wireguide_proto_init() {
	if File_proto_wireguide_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wireguide_proto_rawDesc), len(file_proto_wireguide_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wireguide_proto_goTypes,
		DependencyIndexes: file_proto_wireguide_proto_depIdxs,
		MessageInfos:      file_proto_wireguide_proto_msgTypes,
	}.Build()
	File_proto_wireguide_proto = out.File
	file_proto_wireguide_proto_goTypes = nil
	file_proto_wireguide_proto_depIdxs = nil
}
