// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/wireguide.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WireGuideService_Connect_FullMethodName          = "/wireguide.WireGuideService/Connect"
	WireGuideService_Disconnect_FullMethodName       = "/wireguide.WireGuideService/Disconnect"
	WireGuideService_ListTunnels_FullMethodName      = "/wireguide.WireGuideService/ListTunnels"
	WireGuideService_GetTunnelDetail_FullMethodName  = "/wireguide.WireGuideService/GetTunnelDetail"
	WireGuideService_StreamStatus_FullMethodName     = "/wireguide.WireGuideService/StreamStatus"
	WireGuideService_ImportConfig_FullMethodName     = "/wireguide.WireGuideService/ImportConfig"
	WireGuideService_ValidateConfig_FullMethodName   = "/wireguide.WireGuideService/ValidateConfig"
	WireGuideService_GetConfigText_FullMethodName    = "/wireguide.WireGuideService/GetConfigText"
	WireGuideService_UpdateConfig_FullMethodName     = "/wireguide.WireGuideService/UpdateConfig"
	WireGuideService_DeleteTunnel_FullMethodName     = "/wireguide.WireGuideService/DeleteTunnel"
	WireGuideService_ExportConfig_FullMethodName     = "/wireguide.WireGuideService/ExportConfig"
	WireGuideService_TunnelExists_FullMethodName     = "/wireguide.WireGuideService/TunnelExists"
	WireGuideService_GetSettings_FullMethodName      = "/wireguide.WireGuideService/GetSettings"
	WireGuideService_SaveSettings_FullMethodName     = "/wireguide.WireGuideService/SaveSettings"
	WireGuideService_SetKillSwitch_FullMethodName    = "/wireguide.WireGuideService/SetKillSwitch"
	WireGuideService_SetDNSProtection_FullMethodName = "/wireguide.WireGuideService/SetDNSProtection"
	WireGuideService_Ping_FullMethodName             = "/wireguide.WireGuideService/Ping"
	WireGuideService_Shutdown_FullMethodName         = "/wireguide.WireGuideService/Shutdown"
)

// WireGuideServiceClient is the client API for WireGuideService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WireGuide daemon service.
type WireGuideServiceClient interface {
	// Tunnel operations
	Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error)
	ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error)
	GetTunnelDetail(ctx context.Context, in *GetTunnelDetailRequest, opts ...grpc.CallOption) (*TunnelDetail, error)
	// Real-time status streaming (replaces polling)
	StreamStatus(ctx context.Context, in *StreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionStatus], error)
	// Config management
	ImportConfig(ctx context.Context, in *ImportConfigRequest, opts ...grpc.CallOption) (*ImportConfigResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	GetConfigText(ctx context.Context, in *GetConfigTextRequest, opts ...grpc.CallOption) (*GetConfigTextResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*DeleteTunnelResponse, error)
	ExportConfig(ctx context.Context, in *ExportConfigRequest, opts ...grpc.CallOption) (*ExportConfigResponse, error)
	TunnelExists(ctx context.Context, in *TunnelExistsRequest, opts ...grpc.CallOption) (*TunnelExistsResponse, error)
	// Settings
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*Settings, error)
	SaveSettings(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SaveSettingsResponse, error)
	// Firewall (Phase 2)
	SetKillSwitch(ctx context.Context, in *SetKillSwitchRequest, opts ...grpc.CallOption) (*SetKillSwitchResponse, error)
	SetDNSProtection(ctx context.Context, in *SetDNSProtectionRequest, opts ...grpc.CallOption) (*SetDNSProtectionResponse, error)
	// Daemon management
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type wireGuideServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireGuideServiceClient(cc grpc.ClientConnInterface) WireGuideServiceClient {
	return &wireGuideServiceClient{cc}
}

func (c *wireGuideServiceClient) Connect(ctx context.Context, in *ConnectRequest, opts ...grpc.CallOption) (*ConnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, WireGuideService_Connect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*DisconnectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectResponse)
	err := c.cc.Invoke(ctx, WireGuideService_Disconnect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) ListTunnels(ctx context.Context, in *ListTunnelsRequest, opts ...grpc.CallOption) (*ListTunnelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTunnelsResponse)
	err := c.cc.Invoke(ctx, WireGuideService_ListTunnels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) GetTunnelDetail(ctx context.Context, in *GetTunnelDetailRequest, opts ...grpc.CallOption) (*TunnelDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelDetail)
	err := c.cc.Invoke(ctx, WireGuideService_GetTunnelDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) StreamStatus(ctx context.Context, in *StreamStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConnectionStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WireGuideService_ServiceDesc.Streams[0], WireGuideService_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamStatusRequest, ConnectionStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WireGuideService_StreamStatusClient = grpc.ServerStreamingClient[ConnectionStatus]

func (c *wireGuideServiceClient) ImportConfig(ctx context.Context, in *ImportConfigRequest, opts ...grpc.CallOption) (*ImportConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportConfigResponse)
	err := c.cc.Invoke(ctx, WireGuideService_ImportConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, WireGuideService_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) GetConfigText(ctx context.Context, in *GetConfigTextRequest, opts ...grpc.CallOption) (*GetConfigTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigTextResponse)
	err := c.cc.Invoke(ctx, WireGuideService_GetConfigText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, WireGuideService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) DeleteTunnel(ctx context.Context, in *DeleteTunnelRequest, opts ...grpc.CallOption) (*DeleteTunnelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTunnelResponse)
	err := c.cc.Invoke(ctx, WireGuideService_DeleteTunnel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) ExportConfig(ctx context.Context, in *ExportConfigRequest, opts ...grpc.CallOption) (*ExportConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportConfigResponse)
	err := c.cc.Invoke(ctx, WireGuideService_ExportConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) TunnelExists(ctx context.Context, in *TunnelExistsRequest, opts ...grpc.CallOption) (*TunnelExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TunnelExistsResponse)
	err := c.cc.Invoke(ctx, WireGuideService_TunnelExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, WireGuideService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) SaveSettings(ctx context.Context, in *Settings, opts ...grpc.CallOption) (*SaveSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveSettingsResponse)
	err := c.cc.Invoke(ctx, WireGuideService_SaveSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) SetKillSwitch(ctx context.Context, in *SetKillSwitchRequest, opts ...grpc.CallOption) (*SetKillSwitchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetKillSwitchResponse)
	err := c.cc.Invoke(ctx, WireGuideService_SetKillSwitch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) SetDNSProtection(ctx context.Context, in *SetDNSProtectionRequest, opts ...grpc.CallOption) (*SetDNSProtectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDNSProtectionResponse)
	err := c.cc.Invoke(ctx, WireGuideService_SetDNSProtection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, WireGuideService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireGuideServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, WireGuideService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireGuideServiceServer is the server API for WireGuideService service.
// All implementations must embed UnimplementedWireGuideServiceServer
// for forward compatibility.
//
// WireGuide daemon service.
type WireGuideServiceServer interface {
	// Tunnel operations
	Connect(context.Context, *ConnectRequest) (*ConnectResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error)
	ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error)
	GetTunnelDetail(context.Context, *GetTunnelDetailRequest) (*TunnelDetail, error)
	// Real-time status streaming (replaces polling)
	StreamStatus(*StreamStatusRequest, grpc.ServerStreamingServer[ConnectionStatus]) error
	// Config management
	ImportConfig(context.Context, *ImportConfigRequest) (*ImportConfigResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	GetConfigText(context.Context, *GetConfigTextRequest) (*GetConfigTextResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	DeleteTunnel(context.Context, *DeleteTunnelRequest) (*DeleteTunnelResponse, error)
	ExportConfig(context.Context, *ExportConfigRequest) (*ExportConfigResponse, error)
	TunnelExists(context.Context, *TunnelExistsRequest) (*TunnelExistsResponse, error)
	// Settings
	GetSettings(context.Context, *GetSettingsRequest) (*Settings, error)
	SaveSettings(context.Context, *Settings) (*SaveSettingsResponse, error)
	// Firewall (Phase 2)
	SetKillSwitch(context.Context, *SetKillSwitchRequest) (*SetKillSwitchResponse, error)
	SetDNSProtection(context.Context, *SetDNSProtectionRequest) (*SetDNSProtectionResponse, error)
	// Daemon management
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedWireGuideServiceServer()
}

// UnimplementedWireGuideServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWireGuideServiceServer struct{}

func (UnimplementedWireGuideServiceServer) Connect(context.Context, *ConnectRequest) (*ConnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedWireGuideServiceServer) Disconnect(context.Context, *DisconnectRequest) (*DisconnectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedWireGuideServiceServer) ListTunnels(context.Context, *ListTunnelsRequest) (*ListTunnelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTunnels not implemented")
}
func (UnimplementedWireGuideServiceServer) GetTunnelDetail(context.Context, *GetTunnelDetailRequest) (*TunnelDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTunnelDetail not implemented")
}
func (UnimplementedWireGuideServiceServer) StreamStatus(*StreamStatusRequest, grpc.ServerStreamingServer[ConnectionStatus]) error {
	return status.Error(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedWireGuideServiceServer) ImportConfig(context.Context, *ImportConfigRequest) (*ImportConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportConfig not implemented")
}
func (UnimplementedWireGuideServiceServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedWireGuideServiceServer) GetConfigText(context.Context, *GetConfigTextRequest) (*GetConfigTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigText not implemented")
}
func (UnimplementedWireGuideServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedWireGuideServiceServer) DeleteTunnel(context.Context, *DeleteTunnelRequest) (*DeleteTunnelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTunnel not implemented")
}
func (UnimplementedWireGuideServiceServer) ExportConfig(context.Context, *ExportConfigRequest) (*ExportConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportConfig not implemented")
}
func (UnimplementedWireGuideServiceServer) TunnelExists(context.Context, *TunnelExistsRequest) (*TunnelExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TunnelExists not implemented")
}
func (UnimplementedWireGuideServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*Settings, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedWireGuideServiceServer) SaveSettings(context.Context, *Settings) (*SaveSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveSettings not implemented")
}
func (UnimplementedWireGuideServiceServer) SetKillSwitch(context.Context, *SetKillSwitchRequest) (*SetKillSwitchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetKillSwitch not implemented")
}
func (UnimplementedWireGuideServiceServer) SetDNSProtection(context.Context, *SetDNSProtectionRequest) (*SetDNSProtectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDNSProtection not implemented")
}
func (UnimplementedWireGuideServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedWireGuideServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedWireGuideServiceServer) mustEmbedUnimplementedWireGuideServiceServer() {}
func (UnimplementedWireGuideServiceServer) testEmbeddedByValue()                          {}

// UnsafeWireGuideServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireGuideServiceServer will
// result in compilation errors.
type UnsafeWireGuideServiceServer interface {
	mustEmbedUnimplementedWireGuideServiceServer()
}

func RegisterWireGuideServiceServer(s grpc.ServiceRegistrar, srv WireGuideServiceServer) {
	// If the following call panics, it indicates UnimplementedWireGuideServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WireGuideService_ServiceDesc, srv)
}

func _WireGuideService_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_Connect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).Connect(ctx, req.(*ConnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_Disconnect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_ListTunnels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTunnelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).ListTunnels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_ListTunnels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).ListTunnels(ctx, req.(*ListTunnelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_GetTunnelDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTunnelDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).GetTunnelDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_GetTunnelDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).GetTunnelDetail(ctx, req.(*GetTunnelDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WireGuideServiceServer).StreamStatus(m, &grpc.GenericServerStream[StreamStatusRequest, ConnectionStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WireGuideService_StreamStatusServer = grpc.ServerStreamingServer[ConnectionStatus]

func _WireGuideService_ImportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).ImportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_ImportConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).ImportConfig(ctx, req.(*ImportConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_GetConfigText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).GetConfigText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_GetConfigText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).GetConfigText(ctx, req.(*GetConfigTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_DeleteTunnel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTunnelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).DeleteTunnel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_DeleteTunnel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).DeleteTunnel(ctx, req.(*DeleteTunnelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_ExportConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).ExportConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_ExportConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).ExportConfig(ctx, req.(*ExportConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_TunnelExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TunnelExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).TunnelExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_TunnelExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).TunnelExists(ctx, req.(*TunnelExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_SaveSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Settings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).SaveSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_SaveSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).SaveSettings(ctx, req.(*Settings))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_SetKillSwitch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKillSwitchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).SetKillSwitch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_SetKillSwitch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).SetKillSwitch(ctx, req.(*SetKillSwitchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_SetDNSProtection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDNSProtectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).SetDNSProtection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_SetDNSProtection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).SetDNSProtection(ctx, req.(*SetDNSProtectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireGuideService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireGuideServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireGuideService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireGuideServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WireGuideService_ServiceDesc is the grpc.ServiceDesc for WireGuideService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireGuideService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wireguide.WireGuideService",
	HandlerType: (*WireGuideServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _WireGuideService_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _WireGuideService_Disconnect_Handler,
		},
		{
			MethodName: "ListTunnels",
			Handler:    _WireGuideService_ListTunnels_Handler,
		},
		{
			MethodName: "GetTunnelDetail",
			Handler:    _WireGuideService_GetTunnelDetail_Handler,
		},
		{
			MethodName: "ImportConfig",
			Handler:    _WireGuideService_ImportConfig_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _WireGuideService_ValidateConfig_Handler,
		},
		{
			MethodName: "GetConfigText",
			Handler:    _WireGuideService_GetConfigText_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _WireGuideService_UpdateConfig_Handler,
		},
		{
			MethodName: "DeleteTunnel",
			Handler:    _WireGuideService_DeleteTunnel_Handler,
		},
		{
			MethodName: "ExportConfig",
			Handler:    _WireGuideService_ExportConfig_Handler,
		},
		{
			MethodName: "TunnelExists",
			Handler:    _WireGuideService_TunnelExists_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _WireGuideService_GetSettings_Handler,
		},
		{
			MethodName: "SaveSettings",
			Handler:    _WireGuideService_SaveSettings_Handler,
		},
		{
			MethodName: "SetKillSwitch",
			Handler:    _WireGuideService_SetKillSwitch_Handler,
		},
		{
			MethodName: "SetDNSProtection",
			Handler:    _WireGuideService_SetDNSProtection_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _WireGuideService_Ping_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _WireGuideService_Shutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _WireGuideService_StreamStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/wireguide.proto",
}
