// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config lives in the tunnel's metadata, never in an exported WireGuard file.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("targets" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["targets"] = [];
        }
        if (!("interval_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["interval_seconds"] = 0;
        }
        if (!("failure_threshold" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failure_threshold"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("targets" in $$parsedSource) {
            $$parsedSource["targets"] = $$createField1_0($$parsedSource["targets"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
