// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Rules defines WiFi auto-connect behavior. The model is per-tunnel:
 * each tunnel owns the list of SSIDs that should auto-activate it.
 * The "trusted" list is a global override that disconnects auto-managed
 * tunnels when joining those networks.
 */
export class Rules {
    /**
     * Creates a new Rules instance.
     * @param {Partial<Rules>} [$$source = {}] - The source object to create the Rules.
     */
    constructor($$source = {}) {
        if (!("trusted_ssids" in $$source)) {
            /**
             * override: VPN off on these networks
             * @member
             * @type {string[]}
             */
            this["trusted_ssids"] = [];
        }
        if (!("per_tunnel" in $$source)) {
            /**
             * keyed by tunnel name
             * @member
             * @type {{ [_ in string]?: TunnelSSIDs }}
             */
            this["per_tunnel"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Rules instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Rules}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("trusted_ssids" in $$parsedSource) {
            $$parsedSource["trusted_ssids"] = $$createField0_0($$parsedSource["trusted_ssids"]);
        }
        if ("per_tunnel" in $$parsedSource) {
            $$parsedSource["per_tunnel"] = $$createField1_0($$parsedSource["per_tunnel"]);
        }
        return new Rules(/** @type {Partial<Rules>} */($$parsedSource));
    }
}

/**
 * SSIDPermissionStatus describes whether the process can read the current SSID.
 */
export class SSIDPermissionStatus {
    /**
     * Creates a new SSIDPermissionStatus instance.
     * @param {Partial<SSIDPermissionStatus>} [$$source = {}] - The source object to create the SSIDPermissionStatus.
     */
    constructor($$source = {}) {
        if (!("has_wifi" in $$source)) {
            /**
             * Wi-Fi hardware found
             * @member
             * @type {boolean}
             */
            this["has_wifi"] = false;
        }
        if (!("has_permission" in $$source)) {
            /**
             * SSID access granted (or no WiFi to check)
             * @member
             * @type {boolean}
             */
            this["has_permission"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SSIDPermissionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SSIDPermissionStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SSIDPermissionStatus(/** @type {Partial<SSIDPermissionStatus>} */($$parsedSource));
    }
}

/**
 * TunnelSSIDs holds the per-tunnel auto-connect list. Wrapped in a
 * struct (rather than just []string) so future per-tunnel fields can
 * be added without changing the JSON shape.
 */
export class TunnelSSIDs {
    /**
     * Creates a new TunnelSSIDs instance.
     * @param {Partial<TunnelSSIDs>} [$$source = {}] - The source object to create the TunnelSSIDs.
     */
    constructor($$source = {}) {
        if (!("auto_connect_ssids" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["auto_connect_ssids"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelSSIDs instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelSSIDs}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("auto_connect_ssids" in $$parsedSource) {
            $$parsedSource["auto_connect_ssids"] = $$createField0_0($$parsedSource["auto_connect_ssids"]);
        }
        return new TunnelSSIDs(/** @type {Partial<TunnelSSIDs>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TunnelSSIDs.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
