//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../korjwl1/wireguide/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "files-dropped": $$createType0,
        "reconnect": $$createType1,
        "status": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = main$0.ReconnectEvent.createFrom;
const $$createType2 = main$0.StatusEvent.createFrom;

configure();
