//go:build darwin

package network

import (
	"fmt"
	"log/slog"
	"net"
	"os/exec"
	"strings"
	"sync"
	"time"
)

// DarwinManager implements NetworkManager for macOS, modeled after wg-quick's
// darwin.bash script (github.com/WireGuard/wireguard-tools/src/wg-quick/darwin.bash).
type DarwinManager struct {
	mu sync.Mutex

	// DNS state — saved per service (matches wg-quick collect_new_service_dns).
	// wg-quick sets DNS on EVERY network service, not just the primary one,
	// because macOS can switch primary between Wi-Fi and Ethernet mid-session.
	savedDNS    map[string][]string // service name → original DNS list
	savedSearch map[string][]string // service name → original search domains
	dnsActive   bool

	// Endpoint bypass route state — tracked for cleanup.
	bypassEndpoints []string // IPs we added host routes for

	// Reapply context — stashed during Connect so the route monitor can
	// re-run bypass/DNS/MTU on network changes without needing a config reference.
	lastIface     string
	lastEndpoints []string
	lastDNS       []string
	lastMTU       int
	// lastGatewayV4/V6 remember the upstream default gateway we last anchored
	// our bypass routes to. reapply() compares the live gateway against these
	// and skips the expensive delete+readd cycle if they haven't changed.
	// This is critical: without it, spurious RTM events (including ones
	// generated by our own `route add` commands during Connect) would cause
	// reapply to delete and re-install bypass routes in a tight loop,
	// creating brief windows where encrypted WG packets loop through the
	// tunnel itself and the connection appears dead.
	lastGatewayV4 string
	lastGatewayV6 string

	// Route monitor (wg-quick monitor_daemon equivalent) — only runs for full tunnel.
	monitor *routeMonitor
}

func NewPlatformManager() NetworkManager {
	return &DarwinManager{
		savedDNS:    make(map[string][]string),
		savedSearch: make(map[string][]string),
	}
}

// AssignAddress uses wg-quick's form: `ifconfig <if> inet <ip/cidr> <ip> alias`.
// For IPv6: `ifconfig <if> inet6 <ip/cidr> alias` (no netmask).
func (m *DarwinManager) AssignAddress(ifaceName string, addresses []string) error {
	for _, addr := range addresses {
		ip, _, err := net.ParseCIDR(addr)
		if err != nil {
			return fmt.Errorf("invalid address %q: %w", addr, err)
		}
		if ip.To4() != nil {
			// IPv4: ifconfig <if> inet <cidr> <ip> alias
			if err := run("ifconfig", ifaceName, "inet", addr, ip.String(), "alias"); err != nil {
				return fmt.Errorf("assigning address %s: %w", addr, err)
			}
		} else {
			// IPv6: ifconfig <if> inet6 <cidr> alias
			if err := run("ifconfig", ifaceName, "inet6", addr, "alias"); err != nil {
				return fmt.Errorf("assigning address %s: %w", addr, err)
			}
		}
	}
	return nil
}

// SetMTU uses dynamic detection (wg-quick algorithm): default interface MTU
// minus 80 bytes (40 IPv6 + 8 UDP + 32 WireGuard header overhead).
// Falls back to 1420 if detection fails.
func (m *DarwinManager) SetMTU(ifaceName string, mtu int) error {
	if mtu <= 0 {
		// Auto-detect from default interface
		defaultIf := getDefaultInterface()
		upstreamMTU := 1500
		if defaultIf != "" {
			if v := getInterfaceMTU(defaultIf); v > 0 {
				upstreamMTU = v
			}
		}
		mtu = upstreamMTU - 80
		if mtu < 1280 { // IPv6 minimum
			mtu = 1280
		}
	}
	// Idempotent: skip ifconfig if the interface already has the target MTU.
	// wg-quick's set_mtu_up performs the same check.
	if current := getInterfaceMTU(ifaceName); current == mtu {
		m.mu.Lock()
		m.lastMTU = mtu
		m.mu.Unlock()
		return nil
	}
	if err := run("ifconfig", ifaceName, "mtu", fmt.Sprintf("%d", mtu)); err != nil {
		return err
	}
	m.mu.Lock()
	m.lastMTU = mtu
	m.mu.Unlock()
	return nil
}

func (m *DarwinManager) BringUp(ifaceName string) error {
	return run("ifconfig", ifaceName, "up")
}

// AddRoutes installs routes for AllowedIPs. For /0 (full tunnel) it uses
// the split-route trick + endpoint bypass. Routes are added longest-prefix
// first to avoid transient conflicts (wg-quick's sort -nr -k 2 -t /).
func (m *DarwinManager) AddRoutes(ifaceName string, allowedIPs []string, fullTunnel bool, endpoints []string) error {
	// Sort by prefix length descending (longest first)
	sorted := sortAllowedIPs(allowedIPs)

	hasV4Default := false
	hasV6Default := false
	for _, cidr := range sorted {
		isV6 := strings.Contains(cidr, ":")
		if cidr == "0.0.0.0/0" {
			hasV4Default = true
			continue
		}
		if cidr == "::/0" {
			hasV6Default = true
			continue
		}
		// Non-default route: skip if already pointing at this interface (idempotent)
		family := "-inet"
		if isV6 {
			family = "-inet6"
		}
		if existing, _ := runOut("route", "-n", "get", family, cidr); routeUsesInterface(existing, ifaceName) {
			continue
		}
		if err := run("route", "-q", "-n", "add", family, cidr, "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding route %s: %w", cidr, err)
		}
	}

	// Install default routes using the split trick
	if hasV4Default {
		if err := run("route", "-q", "-n", "add", "-inet", "0.0.0.0/1", "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding 0.0.0.0/1: %w", err)
		}
		if err := run("route", "-q", "-n", "add", "-inet", "128.0.0.0/1", "-interface", ifaceName); err != nil {
			return fmt.Errorf("adding 128.0.0.0/1: %w", err)
		}
	}
	if hasV6Default {
		_ = run("route", "-q", "-n", "add", "-inet6", "::/1", "-interface", ifaceName)
		_ = run("route", "-q", "-n", "add", "-inet6", "8000::/1", "-interface", ifaceName)
	}

	// Add endpoint bypass routes ONLY for the families whose default route
	// we actually hijacked. If a peer endpoint is IPv6 but AllowedIPs only
	// contains 0.0.0.0/0 (IPv4-only full tunnel), the IPv6 default route is
	// untouched — WG packets to the IPv6 peer still flow naturally through
	// the original IPv6 gateway, so NO bypass is needed (and adding one
	// would blackhole a perfectly good path).
	//
	// `endpoints` here are ALREADY-RESOLVED IP LITERALS — the caller
	// (connect_phases) resolved them via the wireguard-go engine at a
	// moment where the tunnel routes were not yet in place. We must never
	// DNS-resolve here, because by this point the /1 split routes above
	// would route the DNS query back through utun, creating a loop.
	//
	// Cache the upstream gateway per family once — one netstat call per
	// family instead of one per endpoint IP.
	var gwV4, gwV6 string
	var gwV4Err, gwV6Err error
	if hasV4Default {
		gwV4, gwV4Err = getDefaultGatewayFor(false)
	}
	if hasV6Default {
		gwV6, gwV6Err = getDefaultGatewayFor(true)
	}
	for _, ipStr := range endpoints {
		if ipStr == "" {
			continue
		}
		ip := net.ParseIP(ipStr)
		if ip == nil {
			slog.Warn("skipping invalid endpoint IP", "ip", ipStr)
			continue
		}
		// Only bypass this endpoint if its family is actually hijacked.
		// See comment above — mis-bypassing a v6 endpoint on a v4-only
		// hijack would blackhole an otherwise-working path.
		isV6 := ip.To4() == nil
		if isV6 && !hasV6Default {
			continue
		}
		if !isV6 && !hasV4Default {
			continue
		}
		if err := m.addBypassForIP(ipStr, gwV4, gwV6, gwV4Err, gwV6Err); err != nil {
			slog.Warn("endpoint bypass route failed", "ip", ipStr, "error", err)
		}
	}

	// Snapshot the current upstream gateway so reapply() can detect genuine
	// changes (Wi-Fi switch etc.) and ignore spurious RTM events.
	currentV4, _ := getDefaultGatewayFor(false)
	currentV6, _ := getDefaultGatewayFor(true)

	// Stash context for reapply on network changes.
	m.mu.Lock()
	m.lastIface = ifaceName
	m.lastEndpoints = append([]string(nil), endpoints...)
	m.lastGatewayV4 = currentV4
	m.lastGatewayV6 = currentV6
	m.mu.Unlock()

	// Start route monitor for full-tunnel mode. Without this, switching Wi-Fi
	// networks would leave the endpoint bypass route pointing at the stale
	// gateway and break the tunnel (wg-quick handles this via monitor_daemon).
	//
	// Start is delayed by 2 seconds so that the RTM_* events emitted by our
	// own `route add` commands above (and any OS-driven chatter immediately
	// after the interface comes up) don't trigger a spurious reapply in the
	// critical handshake window. reapply() itself also gates on
	// lastGatewayV4/V6 changes, so this delay is belt-and-suspenders — but
	// cheap insurance against a class of timing bugs.
	if fullTunnel && len(endpoints) > 0 {
		if m.monitor == nil {
			m.monitor = newRouteMonitor(m.reapply)
		}
		mon := m.monitor
		go func() {
			time.Sleep(2 * time.Second)
			mon.Start()
		}()
	}

	return nil
}

// reapply is invoked by the route monitor on network change events.
// It re-runs the parts of Connect that depend on the upstream default gateway.
//
// CRITICAL: This function only does work when the upstream default gateway
// has ACTUALLY changed since the last time we pinned our bypass routes. The
// route monitor fires on any RTM_* event, including ones generated by our
// own `route add` commands during Connect and by unrelated OS chatter. Doing
// a full delete+readd cycle on every spurious event creates a routing loop
// window where WG encrypted packets go through the tunnel itself, and the
// connection appears dead. Comparing against lastGatewayV4/V6 turns those
// spurious firings into cheap no-ops.
func (m *DarwinManager) reapply() {
	m.mu.Lock()
	iface := m.lastIface
	endpoints := append([]string(nil), m.lastEndpoints...)
	dns := m.lastDNS
	mtu := m.lastMTU
	prevV4 := m.lastGatewayV4
	prevV6 := m.lastGatewayV6
	m.mu.Unlock()

	if iface == "" {
		return
	}

	// Probe the current upstream gateway for each family. Errors here are
	// normal (e.g. no IPv6 connectivity) — we only care about changes.
	currentV4, _ := getDefaultGatewayFor(false)
	currentV6, _ := getDefaultGatewayFor(true)

	if currentV4 == prevV4 && currentV6 == prevV6 {
		// No change — bypass routes are still pointing at the right gateway.
		// Skip the delete+readd cycle entirely.
		return
	}

	slog.Info("route monitor: upstream gateway changed, reapplying",
		"iface", iface,
		"prev_v4", prevV4, "current_v4", currentV4,
		"prev_v6", prevV6, "current_v6", currentV6)

	// Gateway changed — drop the stale bypass routes and re-add via the new
	// gateway. This is the scenario the route monitor was built for (Wi-Fi
	// switch, Ethernet plug-in/out, etc.).
	m.mu.Lock()
	oldBypass := m.bypassEndpoints
	m.bypassEndpoints = nil
	m.mu.Unlock()

	for _, ip := range oldBypass {
		family := "-inet"
		if strings.Contains(ip, ":") {
			family = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", family, ip)
	}

	// Re-resolve gateways once for the new default, then re-add bypass
	// routes. `endpoints` here are the IP literals stashed at Connect time,
	// NOT hostnames — so no DNS is done here either.
	newGwV4, newGwV4Err := getDefaultGatewayFor(false)
	newGwV6, newGwV6Err := getDefaultGatewayFor(true)
	for _, ipStr := range endpoints {
		if ipStr == "" {
			continue
		}
		if err := m.addBypassForIP(ipStr, newGwV4, newGwV6, newGwV4Err, newGwV6Err); err != nil {
			slog.Warn("reapply: bypass failed", "ip", ipStr, "error", err)
		}
	}

	if len(dns) > 0 {
		_ = m.applyDNS(dns)
	}

	if mtu > 0 {
		if current := getInterfaceMTU(iface); current != mtu && current > 0 {
			_ = run("ifconfig", iface, "mtu", fmt.Sprintf("%d", mtu))
		}
	}

	// Remember the new gateway so the next spurious firing is a no-op.
	m.mu.Lock()
	m.lastGatewayV4 = currentV4
	m.lastGatewayV6 = currentV6
	m.mu.Unlock()
}

// addBypassForIP installs a host route for one already-resolved peer endpoint
// IP, pointing at the upstream default gateway. Without this, encrypted WG
// packets destined for the peer would match the /1 split routes and loop
// back through the tunnel itself.
//
// Gateways are passed in (not resolved here) so the caller can make a single
// netstat call for all IPs in a batch — one per family instead of one per IP.
//
// If the gateway probe failed for a given family, we fall back to wg-quick's
// behaviour of installing a blackhole route, which breaks the loop while
// clearly signalling to the user that handshake is impossible in this state.
func (m *DarwinManager) addBypassForIP(ipStr, gwV4, gwV6 string, gwV4Err, gwV6Err error) error {
	ip := net.ParseIP(ipStr)
	if ip == nil {
		return fmt.Errorf("invalid endpoint IP %q", ipStr)
	}
	isV6 := ip.To4() == nil

	var gw string
	var gwErr error
	family := "-inet"
	if isV6 {
		gw = gwV6
		gwErr = gwV6Err
		family = "-inet6"
	} else {
		gw = gwV4
		gwErr = gwV4Err
	}

	recordBypass := func() {
		m.mu.Lock()
		m.bypassEndpoints = append(m.bypassEndpoints, ipStr)
		m.mu.Unlock()
	}

	if gwErr != nil || gw == "" {
		// No usable upstream gateway → install a blackhole so encrypted WG
		// traffic to this peer doesn't loop through the tunnel.
		loopback := "127.0.0.1"
		if isV6 {
			loopback = "::1"
		}
		_ = run("route", "-q", "-n", "add", family, ipStr, loopback, "-blackhole")
		recordBypass()
		return nil
	}

	// Try `route add` first, fall back to `route change` if the kernel
	// already has a route for this host (common when reconnecting).
	if err := run("route", "-q", "-n", "add", family, ipStr, "-gateway", gw); err != nil {
		if err2 := run("route", "-q", "-n", "change", family, ipStr, "-gateway", gw); err2 != nil {
			return fmt.Errorf("bypass route %s via %s: add=%v, change=%v", ipStr, gw, err, err2)
		}
	}
	recordBypass()
	return nil
}

// RemoveRoutes cleans up. wg-quick approach: walk netstat and remove ALL
// routes pointing at this interface, then remove endpoint bypass routes.
// This is more robust than tracking what we added.
func (m *DarwinManager) RemoveRoutes(ifaceName string, allowedIPs []string, fullTunnel bool) error {
	// Stop the route monitor first so its reapply goroutine can't race with
	// teardown. Stop() blocks until any in-flight reapply callback finishes.
	if m.monitor != nil {
		m.monitor.Stop()
	}

	// Remove all routes via this interface (both IPv4 and IPv6)
	m.deleteInterfaceRoutes(ifaceName, "inet")
	m.deleteInterfaceRoutes(ifaceName, "inet6")

	// Snapshot bypass list under the lock, then delete outside.
	m.mu.Lock()
	bypass := m.bypassEndpoints
	m.bypassEndpoints = nil
	m.lastIface = ""
	m.lastEndpoints = nil
	m.lastGatewayV4 = ""
	m.lastGatewayV6 = ""
	m.mu.Unlock()

	for _, ip := range bypass {
		family := "-inet"
		if strings.Contains(ip, ":") {
			family = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", family, ip)
	}
	return nil
}

// deleteInterfaceRoutes walks netstat for the given family and deletes
// every route whose interface (Netif column) matches ifaceName.
// Also handles the wg-quick IPv6 edge case where Netif=lo0 but Gateway=utunN.
func (m *DarwinManager) deleteInterfaceRoutes(ifaceName, family string) {
	out, err := runOut("netstat", "-nr", "-f", family)
	if err != nil {
		return
	}
	// Parse header to find Destination / Gateway / Netif column positions.
	netifIdx, destIdx, gwIdx := -1, -1, -1
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if netifIdx < 0 {
			// Look for header row
			for i, f := range fields {
				switch f {
				case "Destination":
					destIdx = i
				case "Gateway":
					gwIdx = i
				case "Netif":
					netifIdx = i
				}
			}
			continue
		}
		// Require ALL three columns to be in range before indexing, not just
		// Netif — a malformed header could leave destIdx or gwIdx pointing
		// past the line and crash on field access.
		maxIdx := netifIdx
		if destIdx > maxIdx {
			maxIdx = destIdx
		}
		if gwIdx > maxIdx {
			maxIdx = gwIdx
		}
		if len(fields) <= maxIdx || destIdx < 0 || gwIdx < 0 {
			continue
		}
		dest := fields[destIdx]
		gw := fields[gwIdx]
		netif := fields[netifIdx]

		// Match: Netif is our interface, OR (IPv6 only) Netif is lo* and Gateway is our interface
		match := netif == ifaceName
		if !match && family == "inet6" && strings.HasPrefix(netif, "lo") && gw == ifaceName {
			match = true
		}
		if !match {
			continue
		}

		if dest == "default" {
			dest = "0.0.0.0/0"
			if family == "inet6" {
				dest = "::/0"
			}
		}
		famFlag := "-inet"
		if family == "inet6" {
			famFlag = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", famFlag, dest)
	}
}

// routeUsesInterface checks `route get` output for an exact match on the
// interface field. Prevents false matches between utun3 / utun33.
func routeUsesInterface(routeOutput []byte, ifaceName string) bool {
	for _, line := range strings.Split(string(routeOutput), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "interface:") {
			name := strings.TrimSpace(strings.TrimPrefix(line, "interface:"))
			return name == ifaceName
		}
	}
	return false
}

// SetDNS sets DNS on ALL network services (matching wg-quick).
// Entries are split into servers (IPs) and search domains (hostnames),
// mirroring wg-quick's `set_dns` which parses `DNS = 1.1.1.1, corp.example.com`
// that way.
//
// Performance: `networksetup -setdnsservers` is synchronous and slow
// (~150–400 ms per call on a typical Mac). With 5 network services (Wi-Fi,
// Ethernet, Bluetooth PAN, Thunderbolt Bridge, iPhone USB) this can add
// 1.5–4 seconds to Connect if done sequentially. We therefore fan out one
// goroutine per service and wait on them in parallel — they touch different
// resources so there's no contention.
func (m *DarwinManager) SetDNS(ifaceName string, entries []string) error {
	if len(entries) == 0 {
		return nil
	}

	services := getAllNetworkServices()
	if len(services) == 0 {
		return fmt.Errorf("no network services found")
	}

	// Check/update `dnsActive` under the lock — this field is also read by
	// RestoreDNS and (potentially) by reapply via applyDNS, so touching it
	// without the lock is a data race.
	m.mu.Lock()
	alreadyActive := m.dnsActive
	m.mu.Unlock()

	// Save original DNS for each service before overriding (only on first apply).
	// Parallelised: each networksetup -getdnsservers call is ~100–200 ms.
	if !alreadyActive {
		type savedEntry struct {
			svc    string
			dns    []string
			search []string
		}
		saved := make([]savedEntry, len(services))
		var wg sync.WaitGroup
		for i, svc := range services {
			i, svc := i, svc
			wg.Add(1)
			go func() {
				defer wg.Done()
				dns, _ := getCurrentDNS(svc)
				search, _ := getCurrentSearchDomains(svc)
				saved[i] = savedEntry{svc: svc, dns: dns, search: search}
			}()
		}
		wg.Wait()
		m.mu.Lock()
		for _, e := range saved {
			m.savedDNS[e.svc] = e.dns
			m.savedSearch[e.svc] = e.search
		}
		m.mu.Unlock()
	}

	// Push the new DNS to every service in parallel.
	m.applyDNSToServices(entries, services)

	// Flush the macOS DNS cache so lookups see the new servers immediately.
	// Without this users can keep hitting stale resolutions for several
	// minutes — wg-quick does this at the end of its set_dns.
	flushDNSCache()

	m.mu.Lock()
	m.lastDNS = entries
	m.dnsActive = true
	m.mu.Unlock()
	return nil
}

// applyDNS pushes DNS servers and search domains to every network service.
// Does not touch savedDNS/savedSearch — safe to call from reapply().
func (m *DarwinManager) applyDNS(entries []string) error {
	services := getAllNetworkServices()
	m.applyDNSToServices(entries, services)
	flushDNSCache()
	return nil
}

// applyDNSToServices is the shared hot path used by both SetDNS and applyDNS.
// Takes a pre-fetched service list (avoids redundant
// `networksetup -listallnetworkservices` calls) and fans out one goroutine
// per service.
func (m *DarwinManager) applyDNSToServices(entries []string, services []string) {
	servers, search := splitDNSEntries(entries)
	if len(services) == 0 {
		return
	}

	var wg sync.WaitGroup
	for _, svc := range services {
		svc := svc
		wg.Add(1)
		go func() {
			defer wg.Done()
			if len(servers) > 0 {
				args := append([]string{"-setdnsservers", svc}, servers...)
				if err := run("networksetup", args...); err != nil {
					slog.Warn("failed to set DNS on service", "service", svc, "error", err)
				}
			}
			if len(search) > 0 {
				args := append([]string{"-setsearchdomains", svc}, search...)
				if err := run("networksetup", args...); err != nil {
					slog.Warn("failed to set search domains on service", "service", svc, "error", err)
				}
			}
		}()
	}
	wg.Wait()
}

// flushDNSCache tells macOS's mDNSResponder to drop any cached entries so
// lookups see the new DNS servers immediately. Best-effort: errors are not
// propagated because a failed flush is not worth aborting a successful
// Connect over.
func flushDNSCache() {
	_ = run("dscacheutil", "-flushcache")
	_ = run("killall", "-HUP", "mDNSResponder")
}

// splitDNSEntries partitions a mixed DNS list into IP servers and hostname
// search domains, matching wg-quick's parse of `DNS = 1.1.1.1, corp.example.com`.
func splitDNSEntries(entries []string) (servers, search []string) {
	for _, e := range entries {
		e = strings.TrimSpace(e)
		if e == "" {
			continue
		}
		if net.ParseIP(e) != nil {
			servers = append(servers, e)
		} else {
			search = append(search, e)
		}
	}
	return
}

// ResetDNSToSystemDefault clears DNS overrides on every network service
// back to DHCP-provided defaults. Used by crash recovery when the process
// has no memory of the pre-crash DNS state. Parallel across services.
func (m *DarwinManager) ResetDNSToSystemDefault() error {
	services := getAllNetworkServices()
	var wg sync.WaitGroup
	for _, svc := range services {
		svc := svc
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := run("networksetup", "-setdnsservers", svc, "Empty"); err != nil {
				slog.Warn("reset DNS servers failed", "service", svc, "error", err)
			}
			if err := run("networksetup", "-setsearchdomains", svc, "Empty"); err != nil {
				slog.Warn("reset search domains failed", "service", svc, "error", err)
			}
		}()
	}
	wg.Wait()
	flushDNSCache()
	return nil
}

// RestoreDNS restores original DNS for every service we touched. Parallel
// across services — each networksetup call is ~200 ms, and with 5+ services
// the serial version added a full second to every Disconnect.
func (m *DarwinManager) RestoreDNS(ifaceName string) error {
	// Snapshot saved state under the lock, then reset it in the same
	// critical section so any racing SetDNS doesn't see a half-cleared
	// view. dnsActive/savedDNS/savedSearch all live under m.mu.
	m.mu.Lock()
	if !m.dnsActive {
		m.mu.Unlock()
		return nil
	}
	savedDNS := m.savedDNS
	savedSearch := m.savedSearch
	m.savedDNS = make(map[string][]string)
	m.savedSearch = make(map[string][]string)
	m.dnsActive = false
	m.lastDNS = nil
	m.mu.Unlock()

	// Fan out networksetup calls in parallel — each is ~200ms, so for 5+
	// services we save multiple seconds vs serial.
	var wg sync.WaitGroup
	for svc, orig := range savedDNS {
		svc, orig := svc, orig
		wg.Add(1)
		go func() {
			defer wg.Done()
			if len(orig) == 0 {
				_ = run("networksetup", "-setdnsservers", svc, "Empty")
			} else {
				args := append([]string{"-setdnsservers", svc}, orig...)
				_ = run("networksetup", args...)
			}
		}()
	}
	for svc, search := range savedSearch {
		svc, search := svc, search
		wg.Add(1)
		go func() {
			defer wg.Done()
			if len(search) == 0 {
				_ = run("networksetup", "-setsearchdomains", svc, "Empty")
			} else {
				args := append([]string{"-setsearchdomains", svc}, search...)
				_ = run("networksetup", args...)
			}
		}()
	}
	wg.Wait()
	flushDNSCache()
	return nil
}

func (m *DarwinManager) Cleanup(ifaceName string) error {
	if m.monitor != nil {
		m.monitor.Stop()
	}
	_ = m.RestoreDNS(ifaceName)
	// Defensive: remove any remaining routes via this interface
	m.deleteInterfaceRoutes(ifaceName, "inet")
	m.deleteInterfaceRoutes(ifaceName, "inet6")

	m.mu.Lock()
	bypass := m.bypassEndpoints
	m.bypassEndpoints = nil
	m.mu.Unlock()

	for _, ip := range bypass {
		family := "-inet"
		if strings.Contains(ip, ":") {
			family = "-inet6"
		}
		_ = run("route", "-q", "-n", "delete", family, ip)
	}
	return nil
}

// --- helpers ---

func run(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	// Force C locale so parsing English sentinels like "There aren't any DNS Servers"
	// works on non-English macOS systems. wg-quick uses `export LC_ALL=C` at script top.
	cmd.Env = append(cmd.Environ(), "LC_ALL=C", "LANG=C")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w (%s)", name, strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

// runOut runs a command with LC_ALL=C and returns combined output.
// Use for commands where we parse the output.
func runOut(name string, args ...string) ([]byte, error) {
	cmd := exec.Command(name, args...)
	cmd.Env = append(cmd.Environ(), "LC_ALL=C", "LANG=C")
	return cmd.CombinedOutput()
}

// getDefaultGatewayFor returns the IPv4 or IPv6 default gateway, skipping
// link-local entries (link#N) per wg-quick's collect_gateways.
func getDefaultGatewayFor(ipv6 bool) (string, error) {
	family := "inet"
	if ipv6 {
		family = "inet6"
	}
	out, err := runOut("netstat", "-nr", "-f", family)
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		if fields[0] != "default" {
			continue
		}
		gw := fields[1]
		// Skip link-local defaults (point-to-point with no gateway IP)
		if strings.HasPrefix(gw, "link#") {
			continue
		}
		return gw, nil
	}
	return "", fmt.Errorf("no default gateway for %s", family)
}

// getDefaultInterface returns the name of the default route's interface
// by parsing the netstat header to locate the Netif column, then scanning
// for the `default` row. Dynamic header parsing handles column-order
// differences across macOS versions; the previous "first lowercase field"
// heuristic returned `awdl0` (AirDrop) instead of `en0` on some machines.
func getDefaultInterface() string {
	out, err := runOut("netstat", "-nr", "-f", "inet")
	if err != nil {
		return ""
	}
	netifIdx, destIdx := -1, -1
	for _, line := range strings.Split(string(out), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 0 {
			continue
		}
		if netifIdx < 0 {
			for i, f := range fields {
				switch f {
				case "Destination":
					destIdx = i
				case "Netif":
					netifIdx = i
				}
			}
			continue
		}
		if destIdx < 0 || netifIdx < 0 || len(fields) <= netifIdx {
			continue
		}
		if fields[destIdx] == "default" {
			return fields[netifIdx]
		}
	}
	return ""
}

// getInterfaceMTU reads the MTU from ifconfig output.
func getInterfaceMTU(ifaceName string) int {
	out, err := runOut("ifconfig", ifaceName)
	if err != nil {
		return 0
	}
	// Format includes "mtu 1500"
	idx := strings.Index(string(out), "mtu ")
	if idx < 0 {
		return 0
	}
	rest := string(out)[idx+4:]
	var mtu int
	fmt.Sscanf(rest, "%d", &mtu)
	return mtu
}

// getAllNetworkServices returns all network services, including disabled ones.
// wg-quick includes disabled services (strips the "*" prefix) so DNS is
// applied/restored uniformly regardless of current enabled state.
func getAllNetworkServices() []string {
	out, err := runOut("networksetup", "-listallnetworkservices")
	if err != nil {
		return nil
	}
	var services []string
	firstLine := true
	for _, line := range strings.Split(string(out), "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		if firstLine {
			// First non-empty line is the header ("An asterisk...")
			firstLine = false
			continue
		}
		// Strip leading "*" from disabled services (don't skip them)
		if strings.HasPrefix(line, "*") {
			line = strings.TrimSpace(line[1:])
		}
		if line != "" {
			services = append(services, line)
		}
	}
	return services
}

func getCurrentDNS(service string) ([]string, error) {
	out, err := runOut("networksetup", "-getdnsservers", service)
	if err != nil {
		return nil, err
	}
	output := strings.TrimSpace(string(out))
	if strings.Contains(output, "There aren't any DNS Servers") {
		return nil, nil
	}
	var servers []string
	for _, line := range strings.Split(output, "\n") {
		s := strings.TrimSpace(line)
		if s != "" {
			servers = append(servers, s)
		}
	}
	return servers, nil
}

func getCurrentSearchDomains(service string) ([]string, error) {
	out, err := runOut("networksetup", "-getsearchdomains", service)
	if err != nil {
		return nil, err
	}
	output := strings.TrimSpace(string(out))
	if strings.Contains(output, "There aren't any Search Domains") {
		return nil, nil
	}
	var domains []string
	for _, line := range strings.Split(output, "\n") {
		s := strings.TrimSpace(line)
		if s != "" {
			domains = append(domains, s)
		}
	}
	return domains, nil
}

// sortAllowedIPs sorts CIDRs by prefix length descending (longest first),
// matching wg-quick's `sort -nr -k 2 -t /`. Stable order for determinism.
func sortAllowedIPs(cidrs []string) []string {
	result := make([]string, len(cidrs))
	copy(result, cidrs)

	// Simple insertion sort (lists are small, stability guaranteed)
	for i := 1; i < len(result); i++ {
		cur := result[i]
		curPrefix := prefixLen(cur)
		j := i - 1
		for j >= 0 && prefixLen(result[j]) < curPrefix {
			result[j+1] = result[j]
			j--
		}
		result[j+1] = cur
	}
	return result
}

func prefixLen(cidr string) int {
	idx := strings.Index(cidr, "/")
	if idx < 0 {
		return 128
	}
	var n int
	fmt.Sscanf(cidr[idx+1:], "%d", &n)
	return n
}
