// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 */
export const ConnectionStatus = domain$0.ConnectionStatus;

/**
 * ConnectionStatus is re-exported from the domain package so Wails bindings
 * expose the same type that the helper broadcasts — preventing field drift
 * between wire format and frontend expectations.
 * @typedef {domain$0.ConnectionStatus} ConnectionStatus
 */

/**
 * TunnelInfo is the summary shown in the tunnel list.
 */
export class TunnelInfo {
    /**
     * Creates a new TunnelInfo instance.
     * @param {Partial<TunnelInfo>} [$$source = {}] - The source object to create the TunnelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("is_connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["is_connected"] = false;
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelInfo(/** @type {Partial<TunnelInfo>} */($$parsedSource));
    }
}
