// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService is the Wails-bound service.
 * Storage (tunnel files, settings) stays in the GUI process.
 * Tunnel operations go through the helper via an ipc.ClientHolder (so the
 * helper can be re-spawned and the connection swapped without rebuilding
 * the whole service graph).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as diag$0 from "../diag/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as domain$0 from "../domain/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../update/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BaseName extracts the filename without extension from a path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function BaseName(path) {
    return $Call.ByID(3469363575, path);
}

/**
 * CheckConflicts loads a tunnel's config and scans local network interfaces
 * for routing overlaps (e.g. Tailscale, another WireGuard instance). Runs
 * entirely in the GUI process — no IPC needed. The frontend calls this before
 * Connect so it can show a warning dialog if conflicts exist.
 * @param {string} name
 * @returns {$CancellablePromise<diag$0.ConflictInfo[]>}
 */
export function CheckConflicts(name) {
    return $Call.ByID(3480969502, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckForUpdate is the legacy synchronous check kept for backward
 * compatibility with the (now-removed) onMount call. New code should call
 * ManualCheckForUpdate, which routes through the scheduler so the result
 * is also persisted (ETag, last-checked timestamp) and the in-app banner
 * can update without a separate round-trip.
 * @returns {$CancellablePromise<update$0.UpdateInfo | null>}
 */
export function CheckForUpdate() {
    return $Call.ByID(3781738431).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckSSIDPermission reports whether the process can read the current SSID.
 * Used by the frontend to prompt the user for Location Services access before
 * Wi-Fi auto-connect rules can fire.
 * @returns {$CancellablePromise<wifi$0.SSIDPermissionStatus>}
 */
export function CheckSSIDPermission() {
    return $Call.ByID(2549221651).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ClearConnectionHistory wipes the history file.
 * @returns {$CancellablePromise<void>}
 */
export function ClearConnectionHistory() {
    return $Call.ByID(1952295618);
}

/**
 * CloseHistorySessions closes any open history sessions with the given reason.
 * Called from gui.Run during shutdown so the UI doesn't show phantom "Active"
 * rows after a quit.
 * 
 * Single GetStatus probe — the previous one-IPC-per-session pattern made
 * shutdown latency scale linearly with active tunnel count. The status
 * response carries every active tunnel's rx/tx, so one round-trip is enough.
 * Falls back to the lastKnownStats cache (and ultimately zeros) when the
 * helper is already unreachable. Skipped entirely when no sessions are open
 * (the common quit-while-disconnected case) so shutdown stays snappy.
 * @param {string} reason
 * @returns {$CancellablePromise<void>}
 */
export function CloseHistorySessions(reason) {
    return $Call.ByID(2047156944, reason);
}

/**
 * Connect loads a tunnel config from local storage and asks the helper to
 * bring it up. The helper re-validates server-side.
 * 
 * Session lifecycle is owned entirely by ReconcileHistoryFromStatus —
 * opening here would race the helper's StateConnecting status broadcast,
 * which already includes the tunnel name in ActiveTunnels. The race
 * produced spurious "Reconnected" rows on every user-initiated connect
 * before this was unified.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function Connect(name) {
    return $Call.ByID(1123040453, name);
}

/**
 * DeleteTunnel removes a tunnel from local storage. Rejects deletion of the
 * currently connected tunnel (would orphan the interface).
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTunnel(name) {
    return $Call.ByID(3822542112, name);
}

/**
 * Disconnect tears down whatever tunnel the helper currently has active.
 * If the call fails with a "client closed" error (the health monitor may have
 * swapped the client during a recovery), retry once with the fresh client.
 * 
 * We mark lastKnownStats with reason "user" so the upcoming Reconcile (after
 * the next status event with the tunnel gone) labels the closed session as
 * a user disconnect. Existing fresh rx/tx counters from Reconcile's per-tick
 * refresh are preserved — markUserDisconnect overwrites only the reason,
 * not the bytes. This is what protects against rapid double-clicks: the
 * second Disconnect's snapshot may be 0/0 (helper already tearing down)
 * but the cache still holds the fresh values from the steady state.
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(1171530279);
}

/**
 * DisconnectTunnel disconnects a specific tunnel by name. Mirrors
 * Disconnect()'s "client closed" retry: a helper recovery during a
 * per-tunnel disconnect (e.g. user clicks the tray's per-tunnel
 * item right when the health monitor swaps clients) should be
 * transparent, not surfaced as a confusing error.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectTunnel(name) {
    return $Call.ByID(1584259497, name);
}

/**
 * DismissUpdate persists a version dismissal so the in-app banner stays
 * hidden across restarts until a newer version arrives.
 * @param {string} version
 * @returns {$CancellablePromise<void>}
 */
export function DismissUpdate(version) {
    return $Call.ByID(1487086966, version);
}

/**
 * ExportConfig returns the serialized text for display in the export dialog.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig(name) {
    return $Call.ByID(1684823973, name);
}

/**
 * ExportTunnel shows a native save dialog and writes the .conf file.
 * Returns the saved path, or empty string if the user cancelled.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportTunnel(name) {
    return $Call.ByID(686002857, name);
}

/**
 * GetConfigText returns the serialized form of a stored tunnel's config.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigText(name) {
    return $Call.ByID(1065418994, name);
}

/**
 * GetConnectionHistory returns recorded sessions newest-first. Always returns
 * a non-nil slice so the frontend doesn't have to special-case "no history
 * yet" vs. "load failed".
 * @returns {$CancellablePromise<storage$0.Session[]>}
 */
export function GetConnectionHistory() {
    return $Call.ByID(3062937901).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetKnownSSIDs returns the currently-connected SSID (if any) plus the
 * system's saved wireless networks. Both are best-effort — empty values
 * are normal on a Mac that's only ever been on Ethernet.
 * @returns {$CancellablePromise<$models.KnownSSIDs>}
 */
export function GetKnownSSIDs() {
    return $Call.ByID(57262338).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetRoutingTable returns the current OS routing table.
 * @returns {$CancellablePromise<$models.RouteEntry[]>}
 */
export function GetRoutingTable() {
    return $Call.ByID(3049102509).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @returns {$CancellablePromise<storage$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2393200110).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetStatus queries the helper for the current connection status. IPC errors
 * are surfaced to the caller — the frontend needs to distinguish "helper says
 * disconnected" from "helper unreachable".
 * @returns {$CancellablePromise<$models.ConnectionStatus | null>}
 */
export function GetStatus() {
    return $Call.ByID(3544552149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetTunnelDetail returns the full WireGuardConfig for a tunnel. Used by the
 * detail pane to show allowed IPs, DNS, public keys, etc.
 * @param {string} name
 * @returns {$CancellablePromise<domain$0.WireGuardConfig | null>}
 */
export function GetTunnelDetail(name) {
    return $Call.ByID(3171898132, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * GetUpdateState returns persisted state for the About tab UI.
 * @returns {$CancellablePromise<$models.UpdateState>}
 */
export function GetUpdateState() {
    return $Call.ByID(3155746791).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetVersion returns the current app version string.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1775430717);
}

/**
 * ImportConfig parses, validates, and saves a tunnel config under the given
 * name. Returns a TunnelInfo for optimistic UI display.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportConfig(name, content) {
    return $Call.ByID(2459134310, name, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ImportQRFromBytes decodes a QR code from raw image bytes (typically supplied
 * by the file picker, which gives us bytes rather than a path) and imports the
 * resulting WireGuard config.
 * @param {string} data
 * @param {string} name
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportQRFromBytes(data, name) {
    return $Call.ByID(3817928306, data, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ImportQRFromPath reads an image from disk, decodes its QR code, and imports
 * the contained WireGuard config under the given name.
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportQRFromPath(path, name) {
    return $Call.ByID(2544386800, path, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ImportZip extracts all .conf files from a zip archive and imports each one.
 * Returns per-file results; an error is only returned for zip-level failures.
 * @param {string} path
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZip(path) {
    return $Call.ByID(976469479, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ImportZipData imports a zip supplied as raw bytes (used by the file picker,
 * which provides a File object rather than a filesystem path).
 * @param {string} data
 * @returns {$CancellablePromise<$models.ZipImportResult[]>}
 */
export function ImportZipData(data) {
    return $Call.ByID(2432663343, data).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ListTunnels returns every stored tunnel with its summary info.
 * 
 * The active-tunnel marker used to come from an IPC round-trip on every call.
 * That made the tray's rebuild-menu path slow when it was being invoked on
 * the status event stream. The frontend now learns the active tunnel from
 * the status event itself, and the tray caches it internally — so this
 * function stays fully local (disk-only, no IPC) and returns IsConnected
 * purely as a best-effort flag based on a single active-name probe that is
 * safe to skip entirely on slow paths.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnels() {
    return $Call.ByID(3587038916).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * ListTunnelsLocal returns stored tunnels WITHOUT asking the helper which one
 * is active — callers that already know the active name (e.g. the system
 * tray, which tracks it from the status event stream) should use this to
 * avoid an IPC round-trip on every refresh. IsConnected is always false in
 * the returned slice; the caller is responsible for applying its own
 * active-name match.
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnelsLocal() {
    return $Call.ByID(3031176175).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * OpenLocationSettings opens System Settings to the Location Services page so
 * the user can grant SSID access without navigating there manually.
 * @returns {$CancellablePromise<void>}
 */
export function OpenLocationSettings() {
    return $Call.ByID(2515541851);
}

/**
 * OpenURL opens a URL in the default browser. Only HTTPS URLs on
 * github.com are allowed to prevent misuse from a compromised frontend.
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(url) {
    return $Call.ByID(1649174774, url);
}

/**
 * ReadFile reads a file from disk (used by native file drop). Returns the
 * content as a string so the frontend can handle name conflicts before import.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1950850135, path);
}

/**
 * ReconcileHistoryFromStatus is the SINGLE source of truth for opening and
 * closing history sessions. The event bridge calls it on every status event;
 * it diffs the active set against activeSessions and:
 * 
 *   - opens a session for any active tunnel not currently tracked (covers
 *     both user-initiated Connect and helper-driven auto-reconnect / wifi
 *     rules engine / sleep-wake)
 *   - closes a session for any tracked tunnel that has disappeared (using
 *     cached rx/tx + cached reason from lastKnownStats; falls back to
 *     disappearReason — defaults to "reconnect")
 * 
 * Stats cache is always refreshed for currently-active tunnels so disconnect
 * closes have ≤ 1 status-event-tick stale counters. Reason hints set by
 * user-initiated Disconnect / DisconnectTunnel are preserved across cache
 * refreshes — only LoadAndDelete on close clears them.
 * 
 * Fast-path: if the sorted active set hasn't changed since the prior call
 * (the steady-state case at 1 Hz), we skip the activeSessions Range and the
 * open-session loop. The stats cache still gets updated so the eventual
 * disappear-close uses fresh counters.
 * @param {string[]} activeNames
 * @param {{ [_ in string]?: number }} rxByTunnel
 * @param {{ [_ in string]?: number }} txByTunnel
 * @param {string} disappearReason
 * @returns {$CancellablePromise<void>}
 */
export function ReconcileHistoryFromStatus(activeNames, rxByTunnel, txByTunnel, disappearReason) {
    return $Call.ByID(1482043575, activeNames, rxByTunnel, txByTunnel, disappearReason);
}

/**
 * RenameTunnel changes a tunnel's name. Rejects rename of the connected
 * tunnel since the interface name is derived from it.
 * 
 * Routes through the helper's Tunnel.Rename so the active-tunnel check and
 * the file rename both happen under the helper's connectMu — closing the
 * race where a Connect arriving between the GUI's check and the rename
 * could leave the new name in activeCfgs while the file path moved.
 * 
 * Falls back to a direct local rename if the helper rejects the method
 * (older helper that hasn't been upgraded yet).
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTunnel(oldName, newName) {
    return $Call.ByID(576069505, oldName, newName);
}

/**
 * RunDNSLeakTest performs a DNS leak test using the currently active tunnel's
 * DNS servers as the expected (VPN) resolvers. If no tunnel is connected, the
 * expected set is empty — all detected resolvers will be flagged as leaks.
 * @returns {$CancellablePromise<$models.DNSLeakResult | null>}
 */
export function RunDNSLeakTest() {
    return $Call.ByID(2469114850).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType23($result);
    }));
}

/**
 * RunUpdate performs the update end-to-end:
 * 
 *   - Homebrew installs → `brew update && brew upgrade --cask wireguide`,
 *     letting the cask's postflight handle the killall + relaunch. This
 *     is the "one-click" expectation users have, not "copy this command
 *     into your terminal".
 *   - Non-brew installs → open the GitHub Releases page in the browser.
 *     Auto-replacing an un-notarised `.app` bundle needs sudo and races
 *     with Gatekeeper quarantining of the new binary; redirecting the
 *     user to the download page is the honest path for an indie macOS
 *     app without an Apple Developer account.
 * @param {update$0.UpdateInfo | null} info
 * @returns {$CancellablePromise<void>}
 */
export function RunUpdate(info) {
    return $Call.ByID(2959589127, info);
}

/**
 * SaveSettings persists the settings file AND applies any side effects:
 * currently, pushing the new log level to both the GUI's slog handler and
 * the helper's slog handler. Without those side effects a user lowering the
 * level to Debug wouldn't see any new records — the saved file would match
 * the UI but the running process would still be at Info.
 * @param {storage$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3676285513, settings);
}

/**
 * SetApp injects the Wails app for dialog access.
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(1760917394, app);
}

/**
 * SetDNSProtection asks the helper to lock DNS to the active tunnel's servers.
 * When enabling, we look up the active tunnel's DNS list from local storage
 * and pass it along (the helper never touches user-space storage).
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDNSProtection(enabled) {
    return $Call.ByID(472068929, enabled);
}

/**
 * SetHealthCheck enables or disables the tunnel health check monitor.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetHealthCheck(enabled) {
    return $Call.ByID(1079240195, enabled);
}

/**
 * SetKillSwitch asks the helper to enable or disable the firewall kill switch.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetKillSwitch(enabled) {
    return $Call.ByID(1469047591, enabled);
}

/**
 * SetLogLevel updates both the GUI's and the helper's slog level
 * immediately. Exposed as a Wails method so the Settings view can call
 * it without waiting for a full SaveSettings round trip.
 * @param {string} level
 * @returns {$CancellablePromise<void>}
 */
export function SetLogLevel(level) {
    return $Call.ByID(537242663, level);
}

/**
 * SetPinInterface enables or disables -ifscope bypass route pinning.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetPinInterface(enabled) {
    return $Call.ByID(1245113173, enabled);
}

/**
 * SetTunnelLatencyProbeTarget persists the optional per-tunnel ICMP target
 * used only for latency display. The value is deliberately stored outside the
 * WireGuard .conf so exports remain compatible with other clients.
 * @param {string} name
 * @param {string} target
 * @returns {$CancellablePromise<void>}
 */
export function SetTunnelLatencyProbeTarget(name, target) {
    return $Call.ByID(139371444, name, target);
}

/**
 * SetTunnelNotes persists a freeform note for a tunnel. Empty notes still
 * write an empty .meta.json — that matches the contract the frontend
 * expects (write always succeeds, no special-case for "clear").
 * 
 * Existence check first to avoid orphaning a .meta.json sidecar after the
 * .conf was deleted: TunnelDetail's onDestroy can fire-and-forget a
 * pending-edit flush after the user deletes a tunnel, and writing the
 * sidecar in that window would leave a stale file the next tunnel-of-the-
 * same-name would inherit.
 * @param {string} name
 * @param {string} notes
 * @returns {$CancellablePromise<void>}
 */
export function SetTunnelNotes(name, notes) {
    return $Call.ByID(2210192646, name, notes);
}

/**
 * SetUpdateScheduler injects the periodic update-check scheduler and its
 * persistent state store. Called once from gui.Run() after the Wails app
 * is constructed. The frontend's "Check now" / dismiss / last-checked
 * queries route through these.
 * @param {update$0.Scheduler | null} sched
 * @param {update$0.StateStore | null} store
 * @returns {$CancellablePromise<void>}
 */
export function SetUpdateScheduler(sched, store) {
    return $Call.ByID(2970288435, sched, store);
}

/**
 * TunnelExists reports whether a tunnel with the given name is stored.
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function TunnelExists(name) {
    return $Call.ByID(1252108931, name);
}

/**
 * UpdateConfig parses, validates, and overwrites an existing tunnel's config.
 * Rejects edits of the connected tunnel.
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(name, content) {
    return $Call.ByID(660046974, name, content);
}

/**
 * ValidateConfig parses and validates a raw config string. Returns a list of
 * human-readable error messages, or nil if the config is valid.
 * @param {string} content
 * @returns {$CancellablePromise<string[]>}
 */
export function ValidateConfig(content) {
    return $Call.ByID(592398029, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

// Private type creation functions
const $$createType0 = diag$0.ConflictInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = update$0.UpdateInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = wifi$0.SSIDPermissionStatus.createFrom;
const $$createType5 = storage$0.Session.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.KnownSSIDs.createFrom;
const $$createType8 = $models.RouteEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = storage$0.Settings.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = domain$0.ConnectionStatus.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = domain$0.WireGuardConfig.createFrom;
const $$createType15 = $Create.Nullable($$createType14);
const $$createType16 = $models.UpdateState.createFrom;
const $$createType17 = $models.TunnelInfo.createFrom;
const $$createType18 = $Create.Nullable($$createType17);
const $$createType19 = $models.ZipImportResult.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $Create.Array($$createType17);
const $$createType22 = $models.DNSLeakResult.createFrom;
const $$createType23 = $Create.Nullable($$createType22);
const $$createType24 = $Create.Array($Create.Any);
