// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService is the Wails-bound service.
 * Storage (tunnel files, settings) stays in the GUI process.
 * Tunnel operations go through the helper via IPC.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BaseName extracts the filename without extension from a path.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function BaseName(path) {
    return $Call.ByID(3469363575, path);
}

/**
 * @param {string} name
 * @param {boolean} scriptsAllowed
 * @returns {$CancellablePromise<void>}
 */
export function Connect(name, scriptsAllowed) {
    return $Call.ByID(1123040453, name, scriptsAllowed);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTunnel(name) {
    return $Call.ByID(3822542112, name);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(1171530279);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function ExportConfig(name) {
    return $Call.ByID(1684823973, name);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetConfigText(name) {
    return $Call.ByID(1065418994, name);
}

/**
 * @returns {$CancellablePromise<storage$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2393200110).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ConnectionStatus | null>}
 */
export function GetStatus() {
    return $Call.ByID(3544552149).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<config$0.WireGuardConfig | null>}
 */
export function GetTunnelDetail(name) {
    return $Call.ByID(3171898132, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<$models.TunnelInfo | null>}
 */
export function ImportConfig(name, content) {
    return $Call.ByID(2459134310, name, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TunnelInfo[]>}
 */
export function ListTunnels() {
    return $Call.ByID(3587038916).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * ReadFile reads a file from disk (for native file drop).
 * Returns the content as string so the frontend can handle name conflicts.
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function ReadFile(path) {
    return $Call.ByID(1950850135, path);
}

/**
 * @param {storage$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(3676285513, settings);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetDNSProtection(enabled) {
    return $Call.ByID(472068929, enabled);
}

/**
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetKillSwitch(enabled) {
    return $Call.ByID(1469047591, enabled);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<boolean>}
 */
export function TunnelExists(name) {
    return $Call.ByID(1252108931, name);
}

/**
 * @param {string} name
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConfig(name, content) {
    return $Call.ByID(660046974, name, content);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<string[]>}
 */
export function ValidateConfig(content) {
    return $Call.ByID(592398029, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

// Private type creation functions
const $$createType0 = storage$0.Settings.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ConnectionStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.WireGuardConfig.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.TunnelInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType6);
const $$createType9 = $Create.Array($Create.Any);
