// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class InterfaceConfig {
    /**
     * Creates a new InterfaceConfig instance.
     * @param {Partial<InterfaceConfig>} [$$source = {}] - The source object to create the InterfaceConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["mtu"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["listen_port"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pre_up"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["post_up"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pre_down"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["post_down"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InterfaceConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("address" in $$parsedSource) {
            $$parsedSource["address"] = $$createField0_0($$parsedSource["address"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField1_0($$parsedSource["dns"]);
        }
        return new InterfaceConfig(/** @type {Partial<InterfaceConfig>} */($$parsedSource));
    }
}

export class PeerConfig {
    /**
     * Creates a new PeerConfig instance.
     * @param {Partial<PeerConfig>} [$$source = {}] - The source object to create the PeerConfig.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["public_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowed_ips"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["persistent_keepalive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["has_preshared_key"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PeerConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowed_ips" in $$parsedSource) {
            $$parsedSource["allowed_ips"] = $$createField2_0($$parsedSource["allowed_ips"]);
        }
        return new PeerConfig(/** @type {Partial<PeerConfig>} */($$parsedSource));
    }
}

export class TunnelDetail {
    /**
     * Creates a new TunnelDetail instance.
     * @param {Partial<TunnelDetail>} [$$source = {}] - The source object to create the TunnelDetail.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {InterfaceConfig | null | undefined}
             */
            this["interface_config"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {(PeerConfig | null)[] | undefined}
             */
            this["peers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelDetail}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("interface_config" in $$parsedSource) {
            $$parsedSource["interface_config"] = $$createField1_0($$parsedSource["interface_config"]);
        }
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField2_0($$parsedSource["peers"]);
        }
        return new TunnelDetail(/** @type {Partial<TunnelDetail>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = InterfaceConfig.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = PeerConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType4);
