// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InterfaceConfig represents the [Interface] section of a .conf file.
 */
export class InterfaceConfig {
    /**
     * Creates a new InterfaceConfig instance.
     * @param {Partial<InterfaceConfig>} [$$source = {}] - The source object to create the InterfaceConfig.
     */
    constructor($$source = {}) {
        if (!("PrivateKey" in $$source)) {
            /**
             * Required: Base64-encoded 32-byte key
             * @member
             * @type {string}
             */
            this["PrivateKey"] = "";
        }
        if (!("Address" in $$source)) {
            /**
             * Required: CIDR addresses (e.g., "10.0.0.2/24")
             * @member
             * @type {string[]}
             */
            this["Address"] = [];
        }
        if (!("DNS" in $$source)) {
            /**
             * Optional: DNS server addresses
             * @member
             * @type {string[]}
             */
            this["DNS"] = [];
        }
        if (!("MTU" in $$source)) {
            /**
             * Optional: defaults to 0 (auto)
             * @member
             * @type {number}
             */
            this["MTU"] = 0;
        }
        if (!("ListenPort" in $$source)) {
            /**
             * Optional: defaults to 0 (random)
             * @member
             * @type {number}
             */
            this["ListenPort"] = 0;
        }
        if (!("Table" in $$source)) {
            /**
             * Optional: routing table
             * @member
             * @type {string}
             */
            this["Table"] = "";
        }
        if (!("FwMark" in $$source)) {
            /**
             * Optional: firewall mark
             * @member
             * @type {string}
             */
            this["FwMark"] = "";
        }
        if (!("PreUp" in $$source)) {
            /**
             * Optional: script to run before interface up
             * @member
             * @type {string}
             */
            this["PreUp"] = "";
        }
        if (!("PostUp" in $$source)) {
            /**
             * Optional: script to run after interface up
             * @member
             * @type {string}
             */
            this["PostUp"] = "";
        }
        if (!("PreDown" in $$source)) {
            /**
             * Optional: script to run before interface down
             * @member
             * @type {string}
             */
            this["PreDown"] = "";
        }
        if (!("PostDown" in $$source)) {
            /**
             * Optional: script to run after interface down
             * @member
             * @type {string}
             */
            this["PostDown"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InterfaceConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InterfaceConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Address" in $$parsedSource) {
            $$parsedSource["Address"] = $$createField1_0($$parsedSource["Address"]);
        }
        if ("DNS" in $$parsedSource) {
            $$parsedSource["DNS"] = $$createField2_0($$parsedSource["DNS"]);
        }
        return new InterfaceConfig(/** @type {Partial<InterfaceConfig>} */($$parsedSource));
    }
}

/**
 * PeerConfig represents a [Peer] section of a .conf file.
 */
export class PeerConfig {
    /**
     * Creates a new PeerConfig instance.
     * @param {Partial<PeerConfig>} [$$source = {}] - The source object to create the PeerConfig.
     */
    constructor($$source = {}) {
        if (!("PublicKey" in $$source)) {
            /**
             * Required: Base64-encoded 32-byte key
             * @member
             * @type {string}
             */
            this["PublicKey"] = "";
        }
        if (!("PresharedKey" in $$source)) {
            /**
             * Optional: Base64-encoded 32-byte key
             * @member
             * @type {string}
             */
            this["PresharedKey"] = "";
        }
        if (!("Endpoint" in $$source)) {
            /**
             * Optional: host:port
             * @member
             * @type {string}
             */
            this["Endpoint"] = "";
        }
        if (!("AllowedIPs" in $$source)) {
            /**
             * Required: CIDR addresses
             * @member
             * @type {string[]}
             */
            this["AllowedIPs"] = [];
        }
        if (!("PersistentKeepalive" in $$source)) {
            /**
             * Optional: seconds, 0 = disabled
             * @member
             * @type {number}
             */
            this["PersistentKeepalive"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PeerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PeerConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AllowedIPs" in $$parsedSource) {
            $$parsedSource["AllowedIPs"] = $$createField3_0($$parsedSource["AllowedIPs"]);
        }
        return new PeerConfig(/** @type {Partial<PeerConfig>} */($$parsedSource));
    }
}

/**
 * WireGuardConfig represents a complete WireGuard configuration file.
 */
export class WireGuardConfig {
    /**
     * Creates a new WireGuardConfig instance.
     * @param {Partial<WireGuardConfig>} [$$source = {}] - The source object to create the WireGuardConfig.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * Tunnel name (derived from filename)
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Interface" in $$source)) {
            /**
             * [Interface] section
             * @member
             * @type {InterfaceConfig}
             */
            this["Interface"] = (new InterfaceConfig());
        }
        if (!("Peers" in $$source)) {
            /**
             * [Peer] sections (1 or more)
             * @member
             * @type {PeerConfig[]}
             */
            this["Peers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WireGuardConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WireGuardConfig}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Interface" in $$parsedSource) {
            $$parsedSource["Interface"] = $$createField1_0($$parsedSource["Interface"]);
        }
        if ("Peers" in $$parsedSource) {
            $$parsedSource["Peers"] = $$createField2_0($$parsedSource["Peers"]);
        }
        return new WireGuardConfig(/** @type {Partial<WireGuardConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = InterfaceConfig.createFrom;
const $$createType2 = PeerConfig.createFrom;
const $$createType3 = $Create.Array($$createType2);
