// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "./internal/app/models.js";

/**
 * StatusEvent is broadcast to the frontend whenever tunnel status changes.
 */
export class StatusEvent {
    /**
     * Creates a new StatusEvent instance.
     * @param {Partial<StatusEvent>} [$$source = {}] - The source object to create the StatusEvent.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (!("interface_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface_name"] = "";
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (!("last_handshake" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_handshake"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["duration"] = "";
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StatusEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StatusEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StatusEvent(/** @type {Partial<StatusEvent>} */($$parsedSource));
    }
}

/**
 * TunnelsEvent is broadcast when the tunnel list changes.
 */
export class TunnelsEvent {
    /**
     * Creates a new TunnelsEvent instance.
     * @param {Partial<TunnelsEvent>} [$$source = {}] - The source object to create the TunnelsEvent.
     */
    constructor($$source = {}) {
        if (!("tunnels" in $$source)) {
            /**
             * @member
             * @type {app$0.TunnelInfo[]}
             */
            this["tunnels"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelsEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelsEvent}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tunnels" in $$parsedSource) {
            $$parsedSource["tunnels"] = $$createField0_0($$parsedSource["tunnels"]);
        }
        return new TunnelsEvent(/** @type {Partial<TunnelsEvent>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = app$0.TunnelInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
