// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ConnectionStatus represents the current state of a tunnel connection.
 */
export class ConnectionStatus {
    /**
     * Creates a new ConnectionStatus instance.
     * @param {Partial<ConnectionStatus>} [$$source = {}] - The source object to create the ConnectionStatus.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (!("interface_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["interface_name"] = "";
        }
        if (!("connected_at" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["connected_at"] = null;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["duration"] = "";
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (!("last_handshake" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["last_handshake"] = null;
        }
        if (!("handshake_age" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["handshake_age"] = "";
        }
        if (!("endpoint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["endpoint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionStatus(/** @type {Partial<ConnectionStatus>} */($$parsedSource));
    }
}

/**
 * State represents the tunnel connection state.
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateDisconnected: "disconnected",
    StateConnecting: "connecting",
    StateConnected: "connected",
    StateError: "error",
};
