// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Session is one VPN session record. EndTime is a pointer so a still-active
 * session (no end yet) can be distinguished from a completed session that
 * happens to have ended at time.Time{} — the previous flat-struct design
 * couldn't tell those apart and showed phantom "0s" rows in the UI when the
 * helper was killed mid-connect before the disconnect path could write
 * final stats.
 */
export class Session {
    /**
     * Creates a new Session instance.
     * @param {Partial<Session>} [$$source = {}] - The source object to create the Session.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tunnel_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tunnel_name"] = "";
        }
        if (!("start_time" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["start_time"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {time$0.Time | null | undefined}
             */
            this["end_time"] = undefined;
        }
        if (!("duration_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_sec"] = 0;
        }
        if (!("rx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rx_bytes"] = 0;
        }
        if (!("tx_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tx_bytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["disconnect_reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Session instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Session}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Session(/** @type {Partial<Session>} */($$parsedSource));
    }
}

/**
 * Settings holds application-wide settings.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * "auto", "en", "ko", "ja"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * "dark", "light", "system"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("tray_icon_style" in $$source)) {
            /**
             * "color" (MVP: color only)
             * @member
             * @type {string}
             */
            this["tray_icon_style"] = "";
        }
        if (!("auto_start" in $$source)) {
            /**
             * launch GUI on OS login
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }
        if (!("kill_switch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["kill_switch"] = false;
        }
        if (!("dns_protection" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dns_protection"] = false;
        }
        if (!("health_check" in $$source)) {
            /**
             * periodic handshake age monitoring
             * @member
             * @type {boolean}
             */
            this["health_check"] = false;
        }
        if (!("pin_interface" in $$source)) {
            /**
             * pin bypass routes to upstream interface (-ifscope)
             * @member
             * @type {boolean}
             */
            this["pin_interface"] = false;
        }
        if (!("log_level" in $$source)) {
            /**
             * "debug", "info", "warn", "error"
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * AutoUpdateCheck controls the periodic update scheduler. *bool so we
             * can distinguish "user never touched this" from "user explicitly
             * turned it off" — defaults to true on first load. A user who installs
             * via brew might prefer to disable in-app checks and let brew handle
             * it instead; an offline / corporate-network user might disable to
             * silence the failed-check log noise.
             * @member
             * @type {boolean | null | undefined}
             */
            this["auto_update_check"] = undefined;
        }
        if (!("wifi_rules" in $$source)) {
            /**
             * WifiRules holds the SSID-based auto-connect / auto-disconnect
             * policy. Per-tunnel auto-connect SSIDs are managed in TunnelDetail;
             * trusted SSIDs (global disconnect on join) are managed in Settings.
             * @member
             * @type {wifi$0.Rules}
             */
            this["wifi_rules"] = (new wifi$0.Rules());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wifi_rules" in $$parsedSource) {
            $$parsedSource["wifi_rules"] = $$createField10_0($$parsedSource["wifi_rules"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = wifi$0.Rules.createFrom;
