// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as wifi$0 from "../wifi/models.js";

/**
 * Settings holds application-wide settings.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("language" in $$source)) {
            /**
             * "auto", "en", "ko", "ja"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("theme" in $$source)) {
            /**
             * "dark", "light", "system"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("tray_icon_style" in $$source)) {
            /**
             * "color" (MVP: color only)
             * @member
             * @type {string}
             */
            this["tray_icon_style"] = "";
        }
        if (!("auto_start" in $$source)) {
            /**
             * launch GUI on OS login
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }
        if (!("kill_switch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["kill_switch"] = false;
        }
        if (!("dns_protection" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["dns_protection"] = false;
        }
        if (!("health_check" in $$source)) {
            /**
             * periodic handshake age monitoring
             * @member
             * @type {boolean}
             */
            this["health_check"] = false;
        }
        if (!("pin_interface" in $$source)) {
            /**
             * pin bypass routes to upstream interface (-ifscope)
             * @member
             * @type {boolean}
             */
            this["pin_interface"] = false;
        }
        if (!("log_level" in $$source)) {
            /**
             * "debug", "info", "warn", "error"
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }
        if (!("wifi_rules" in $$source)) {
            /**
             * WifiRules holds the SSID-based auto-connect / auto-disconnect
             * policy. Disabled by default; the frontend Settings panel toggles
             * it and per-SSID mappings. Evaluated by the GUI on each SSID
             * change broadcast from the helper.
             * @member
             * @type {wifi$0.Rules}
             */
            this["wifi_rules"] = (new wifi$0.Rules());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("wifi_rules" in $$parsedSource) {
            $$parsedSource["wifi_rules"] = $$createField9_0($$parsedSource["wifi_rules"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = wifi$0.Rules.createFrom;
