package gui

import (
	_ "embed"
	"log/slog"
	"runtime"
	"sync"

	wgapp "github.com/korjwl1/wireguide/internal/app"
	"github.com/wailsapp/wails/v3/pkg/application"
	"github.com/wailsapp/wails/v3/pkg/icons"
)

// trayOnIcon is the menu-bar icon used while a tunnel is connected. Same W
// glyph as icons.SystrayMacTemplate (the Wails default tray W) with a small
// green dot in the bottom-right corner. Generated by qlmanage from
// build/icon/tray-on.svg; see that file for provenance.
//
// It's a COLOURED icon (SetIcon, not SetTemplateIcon) because template
// icons are rendered as a monochrome mask and the green dot would
// blacken — defeating the entire point of using colour to signal "live".
//
//go:embed tray-on.png
var trayOnIcon []byte

// trayManager owns the system tray menu and its visual state.
//
// There are TWO update paths, intentionally separate:
//
//  1. setIconState(activeName) — cheap, called from the status event stream
//     every second. Only touches label + tooltip. NO IPC, NO disk I/O, so it
//     never blocks the event loop goroutine.
//
//  2. rebuildMenu() — expensive, rebuilds the full tunnel list in the menu.
//     Called only on user actions that change the list (add, delete, rename)
//     or on explicit refresh after connect/disconnect finishes.
//
// The previous design called the full rebuildMenu on every status event and
// did an IPC round-trip to the helper inside ListTunnels — that blocked the
// event stream, making the UI feel sluggish under a 1 Hz status broadcast.
type trayManager struct {
	app        *application.App
	tray       *application.SystemTray
	svc        *wgapp.TunnelService
	doShutdown func()

	mu           sync.Mutex
	activeTunnel string // cached from status events, avoids MethodActiveName IPC
}

func newTrayManager(app *application.App, tray *application.SystemTray, svc *wgapp.TunnelService, doShutdown func()) *trayManager {
	return &trayManager{
		app:        app,
		tray:       tray,
		svc:        svc,
		doShutdown: doShutdown,
	}
}

// initialBuild draws the menu once at startup.
func (t *trayManager) initialBuild() {
	t.rebuildMenu()
}

// setIconState swaps the tray ICON (not a text label) based on connection
// state, and updates the tooltip. Called from the status event stream, so
// it must stay O(1) — no IPC, no disk I/O.
//
//   disconnected → Wails's default template W (monochrome, auto-inverts)
//   connected    → coloured W with a green dot badge (non-template)
//
// Previously we used SetLabel("●") next to the template icon, but the user
// wanted the dot as a badge on the glyph itself, not as a neighbouring
// character. Two separate icon assets is the only way to achieve that on
// macOS's menu bar — template icons can't carry colour.
func (t *trayManager) setIconState(activeName string) {
	t.mu.Lock()
	prev := t.activeTunnel
	t.activeTunnel = activeName
	t.mu.Unlock()

	if activeName != "" {
		t.tray.SetIcon(trayOnIcon)
		t.tray.SetTooltip("WireGuide — connected: " + activeName)
	} else {
		// Back to the default template W. On macOS this auto-inverts with
		// the menu-bar theme; on Linux/Windows we fall through to the
		// label-text path since there's no template rendering there.
		if runtime.GOOS == "darwin" {
			t.tray.SetTemplateIcon(icons.SystrayMacTemplate)
		}
		t.tray.SetTooltip("WireGuide")
	}

	// Non-macOS: fall back to a text label suffix since they don't
	// render template icons the same way. Harmless on macOS (label is
	// only shown alongside template icons, not coloured ones).
	if runtime.GOOS != "darwin" {
		if activeName != "" {
			t.tray.SetLabel("WireGuide ●")
		} else {
			t.tray.SetLabel("WireGuide")
		}
	}

	// When the active tunnel actually changes (not just a stats tick), we
	// also need to update the menu's ●/○ glyphs. The menu rebuild is O(n)
	// over the tunnel list + disk reads, so we do it off the caller's
	// goroutine to keep the event loop moving.
	if prev != activeName {
		go t.rebuildMenu()
	}
}

// rebuildMenu reconstructs the whole tray menu: tunnel list, Show Window,
// Quit. Uses ListTunnelsLocal (disk only, no IPC) + the cached activeTunnel
// for connected-state glyphs. Safe to invoke from any goroutine.
func (t *trayManager) rebuildMenu() {
	tunnels, err := t.svc.ListTunnelsLocal()
	if err != nil {
		slog.Debug("tray: list tunnels failed", "error", err)
	}

	t.mu.Lock()
	activeName := t.activeTunnel
	t.mu.Unlock()

	m := t.app.NewMenu()
	m.Add("WireGuide").SetEnabled(false)
	m.AddSeparator()

	for _, tun := range tunnels {
		tun := tun // loop-var capture
		connected := tun.Name == activeName
		label := "○ " + tun.Name
		if connected {
			label = "● " + tun.Name
		}
		m.Add(label).OnClick(func(ctx *application.Context) {
			if connected {
				_ = t.svc.Disconnect()
			} else {
				_ = t.svc.Connect(tun.Name, false)
			}
			// Rebuild happens via the status event from the helper.
		})
	}
	m.AddSeparator()
	m.Add("Show Window").OnClick(func(ctx *application.Context) { t.app.Show() })
	m.AddSeparator()
	m.Add("Quit").OnClick(func(ctx *application.Context) {
		t.doShutdown()
		t.app.Quit()
	})
	t.tray.SetMenu(m)
}
