// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * UpdateInfo contains information about an available update.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("release_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_url"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("release_notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_notes"] = "";
        }
        if (!("asset_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["asset_name"] = "";
        }
        if (!("asset_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["asset_size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * URL to SHA256SUMS file
             * @member
             * @type {string | undefined}
             */
            this["checksum_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * pre-parsed SHA256 for this asset
             * @member
             * @type {string | undefined}
             */
            this["expected_hash"] = undefined;
        }
        if (!("hash_verified" in $$source)) {
            /**
             * set to true after successful checksum verification
             * @member
             * @type {boolean}
             */
            this["hash_verified"] = false;
        }
        if (!("signature_verified" in $$source)) {
            /**
             * true iff Ed25519 .sig also verified
             * @member
             * @type {boolean}
             */
            this["signature_verified"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}
